### ISSUE TITLE
Heavy Rain

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#100]
Just installed a new tempest replacement unit and it rain like crazy the unit reported heavy rain  home assint reported light rain or no rain cleared mqtt and the same results anyone else notice a change in reporting ?

Temp reporting  Moderate Ha say light rain

**Comment by GlennGoddard** [comment]
I will hopefully remember to compare next time we get rain (probably tomorrow).
I can't remember seeing a difference in the past, but things do change.

Looks like WeatherFlow is having problems on the server side.  The app for me is not reporting all information, but locally I have everything.

**Comment by briis** [comment]
Have you checked that your Hub is still online? Is the green light on in the back?
I have to reboot mine about every month.

**Comment by robertw** [comment]
My unit died the sensors stop functioning they replaced it looks like a new one. Yes it's connected to the hub just fine and maintains a strong connection.....

**Comment by natekspencer** [comment]
@robertw are you on imperial or metric? It looks like there is a bug if set to imperial which I'll be addressing.

**Comment by robertw** [comment]
Just a fyi on new build 3.03 they say light rain ours says heavy and yes on  imperial

**Comment by briis** [comment]
> Just a fyi on new build 3.03 they say light rain ours says heavy and yes on imperial

Not sure what you mean by that. Has nothing changed?

**Comment by robertw** [comment]
Nope tempest says light rain plugin days the word heavy....

**Comment by briis** [comment]
@natekspencer Did we reverse the function?

**Comment by natekspencer** [comment]
The function stayed the same. Previously, however, the rain rate was being converted to imperial first and then compared against a millimeter value for intensity, so it was always low.

What would be helpful here is to see the rain rate and the rain intensity as reported in Home Assistant, so we can verify the function. And to also see the output from the Tempest app during the same period to see WeatherFlow's interpretation.

I'm not sure where the conversion calculation numbers come from, but maybe we could verify those as well.

**Comment by briis** [comment]
Agree with @natekspencer. Next time it rains, could you record the data he specifies and post them here. I just checked the formula, and nothing has changed. It works for me, so there must be something with the data.

**Comment by robertw** [comment]
Will do 👍

**Comment by GlennGoddard** [comment]
I currently have heavy rain reported via this integration and the WF app.

**Comment by briis** [comment]
This should be fixed. Please re-open if that is not the case.
