### ISSUE TITLE
Last Lightning Strike & Last Rain Start are off

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#101]
Just updated to the last dev build and the reported time is "52 years ago" for Last Lightning Strike and Last Rain Start.
I will look in the code when I get a chance, but I just noticed it on this last update.

Pulled from MQTT:
rain_start_time: 1969-12-31T16:00:00
lightning_strike_time: 1969-12-31T16:00:00

**Comment by briis** [comment]
Hi Glenn,
Yes I forgot to mention in the release notes. Local data are now stored in /data so you must change the `-v $(pwd): /usr/local/config` and change this to `-v $(pwd):/data`, that should then pick-up your data again.

**Comment by GlennGoddard** [comment]
That did the trick.
What the change of the storage related to having it work with Add-Ons?

**Comment by briis** [comment]
Yes, this is the standard for how Add-On's should be setup. 
@natekspencer who did the Add-On support is now also working to re-write a lot of the code to make it easier to maintain going forward, and utilize some already existing Libraries.
