### ISSUE TITLE
Null value in forecast

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#104]
I am getting null/empty values for some fields in one of the forecast elements that is causing issues with my weather card (it is highly customized for my particular needs, but based one of the popular custom cards).  Have not seen this before so it is probably pretty rare, but suspect it is incoming from the WeatherFlow forecast data.

I am going to trap for this in my weather-card but thought I would share in case it is something you want to address.  I only use my own weather-card, so don't know if this would impact others, and it is probably unlikely to occur very often from the upstream forecast anyway.

As always,  Thank you.

- datetime: '2021-12-03T19:00:00+00:00'
  conditions: ''
  condition: null
  temperature: 73.4
  pressure: 30.002
  humidity: 69
  precipitation: 0
  precipitation_probability: 40
  precip_icon: chance-rain
  precip_type: ''
  wind_speed: 6.71
  wind_gust: 6.71
  wind_bearing: 186
  wind_direction_cardinal: S
  uv: 3
  feels_like: 75.2

**Comment by briis** [comment]
Sorry, I cannot replicate this. Below is a resent pick from my `sensor.wf_weather` and the Hourly Forecast. I have all data filled. Try and activate the Debug function, and see if something shows in the log. 

````
- datetime: '2021-12-04T13:00:00+00:00'
  conditions: Cloudy
  condition: cloudy
  temperature: 4
  pressure: 998.16
  humidity: 93
  precipitation: 0
  precipitation_probability: 5
  precip_icon: chance-sleet
  precip_type: sleet
  wind_speed: 3.6
  wind_gust: 3.6
  wind_bearing: 60
  wind_direction_cardinal: ØNØ
  uv: 0
````

**Comment by chasut** [comment]
Not surprised, I haven't seen anything like this and have been running pretty much from the beginning.  It must have been something on the Weatherflow forecast end.  I am now trapping for the null value on my end now, but the forecast element with the null is now gone, and probably never to return.

But as I thought about it, even if you did receive a Null for condition from the WF forecast api, the appropriate action would be to pass it along.  So, this is just a curiosity with no action warranted.

Thanks again for maintaining this (and other) wonderful projects
