### ISSUE TITLE
HA 2021.12 beta

### ISSUE THREAD

**Issue by leonardpitzu** [briis/hass-weatherflow2mqtt#105]
i get a bunch of these errors in HA:

`Exception in message_received when handling msg on 'homeassistant/sensor/weatherflow2mqtt/obs_air/state': '{"station_pressure": 948.18, "air_temperature": 0.9, "relative_humidity": 96.18, "lightning_strike_count": 5, "lightning_strike_count_1hr": 158, "lightning_strike_count_3hr": 495, "lightning_strike_count_today": 1191, "lightning_strike_distance": 17, "lightning_strike_energy": 16798251, "lightning_strike_time": "2021-12-04T09:18:38.797171", "sealevel_pressure": 1011.82, "pressure_trend": "Steady", "pressure_trend_value": 0, "air_density": 1.21, "dewpoint": 0.4, "feelslike": -2.0, "wetbulb": 0.7, "delta_t": 0.2, "visibility": 2.1, "absolute_humidity": 4.97, "wbgt": -1.1, "dewpoint_description": "Somewhat Dry", "temperature_description": "Cold", "last_reset_midnight": "2021-12-03T22:00:00+00:00"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 502, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 508, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.wf_last_lightning_strike provides state '2021-12-04 09:18:38.797171', which is missing timezone information`

and

`Exception in message_received when handling msg on 'homeassistant/sensor/weatherflow2mqtt/obs_air/state': '{"station_pressure": 948.18, "air_temperature": 0.9, "relative_humidity": 96.53, "lightning_strike_count": 6, "lightning_strike_count_1hr": 160, "lightning_strike_count_3hr": 493, "lightning_strike_count_today": 1186, "lightning_strike_distance": 12, "lightning_strike_energy": 16820479, "lightning_strike_time": "2021-12-04T09:17:40.955674", "sealevel_pressure": 1011.82, "pressure_trend": "Steady", "pressure_trend_value": 0, "air_density": 1.21, "dewpoint": 0.4, "feelslike": -1.1, "wetbulb": 0.7, "delta_t": 0.2, "visibility": 2.1, "absolute_humidity": 4.99, "wbgt": -1.1, "dewpoint_description": "Somewhat Dry", "temperature_description": "Cold", "last_reset_midnight": "2021-12-03T22:00:00+00:00"}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 502, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 508, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.wf_last_lightning_strike provides state '2021-12-04 09:17:40.955674', which is missing timezone information`

**Comment by briis** [comment]
I am releasing V2.2.5 as this is written, and with this, the issue should be gone.

**Comment by leonardpitzu** [comment]
Confirmed fixed, thanks.
