### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#106]
Just installed Ha version 2.2.5
Ha 2021.11.5
MQTT Current version: 6.0.1 

Version | core-2021.11.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.17-v8
CPU Architecture | aarch64
Timezone | America/New_York

Config default 

 INFO:weatherflow2mqtt.weatherflow_mqtt:SETTING UP TEMPEST Status SENSOR
Traceback (most recent call last):
  File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>
    sys.exit(load_entry_point('weatherflow2mqtt==2.2.5', 'console_scripts', 'weatherflow2mqtt')())
  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-2.2.5-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-2.2.5-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 843, in main
  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-2.2.5-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 627, in listen
TypeError: cannot unpack non-iterable NoneType object

**Comment by robertw** [comment]
Update moved back to outside of HA on a standalone install  seems to running fine but reporting windspeed other sensors from hub seem to be a bit slower as per updating 

but also getting a few of these on this installation 
DEBUG:weatherflow2mqtt.weatherflow_mqtt:Device ST-00051410 has reported a sensor fault. Reason: ['lightning failed']

**Comment by briis** [comment]
> but reporting windspeed other sensors from hub seem to be a bit slower as per updating

If you, like me, live in a place where the days get shorter in the winter, then your device will not get enough sunlight to properly charge the batteries, and instead of shutting down, WeatherFlow is changing the reporting interval, as you can see below. That might be the reason for slower updates.

````
Power Save Modes
Here are details on how the Tempest may conserve power in order to operate for as long as possible. Most Tempests never go below Mode 0 and more than 90% will never go below Mode 1.

Mode 0: Voltage ≥ 2.455

All sensors enabled and operating at full performance
Wind sampling interval every 3 seconds

Mode 1: Voltage ≤ 2.415 from Mode 0 or ≥  2.41 from Mode 2
Wind sampling interval set to 6 seconds

Mode 2: Voltage ≤ 2.39 from Mode 1 or ≥  2.375 from Mode 3
Wind sampling interval set to one minute

Mode 3: Voltage ≤ 2.355
Wind sampling interval set to 5 minutes
All other sensors' sampling interval set to 5 minutes
Haptic Rain sensor disabled from active listening
````


> DEBUG:weatherflow2mqtt.weatherflow_mqtt:Device ST-00051410 has reported a sensor fault. Reason: ['lightning failed']


This is not an error, but just telling you that there might be something close to your Weather Station that creates interference.
