### ISSUE TITLE
No UDP data in v3.0.0

### ISSUE THREAD

**Issue by summitbri** [briis/hass-weatherflow2mqtt#109]
After upgrading the add-on in HA, I see the new mqtt topic and sensors created with the Tempest ID, but no data is available in the new sensors.  Is it necessary to install the pyweatherudp package somewhere separately?

**Comment by briis** [comment]
`pyweatherflowudp` is installed by in the container, so no need to add that.
I saw the same behaviour, try and do a hard refresh of your browser and see if the sensors are not being populated.

Else turn on the Debug flag, and look in the log to see if anything shows up.

**Comment by summitbri** [comment]
Hard refresh didn't make a difference.  Debug log captures a few events upon restart and then appears to stop when reaching hub_status.

INFO:weatherflow2mqtt.weatherflow_mqtt:🏠 Home Assistant Supervisor Mode 🏠
INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is America/Denver
INFO:weatherflow2mqtt.weatherflow_mqtt:Connected to the MQTT server at core-mosquitto:1883
DEBUG:pyweatherflowudp.client:Started listening
INFO:weatherflow2mqtt.weatherflow_mqtt:The UDP server is listening on port 50222
DEBUG:pyweatherflowudp.client:Received message from 172.30.32.1:49270 - b'{"serial_number":"ST-00050852","type":"rapid_wind","hub_sn":"HB-00063380","ob":[1639156896,11.30,317]}'
DEBUG:pyweatherflowudp.client:Received message from 172.30.32.1:49270 - b'{"serial_number":"ST-00050852","type":"rapid_wind","hub_sn":"HB-00063380","ob":[1639156899,8.39,318]}'
DEBUG:pyweatherflowudp.client:Received message from 172.30.32.1:49270 - b'{"serial_number":"HB-00063380","type":"hub_status","firmware_revision":"177","uptime":1187205,"rssi":-37,"timestamp":1639156900,"reset_flags":"BOR,PIN,POR","seq":118572,"radio_stats":[25,1,0,3,4364],"mqtt_stats":[436,15]}'

**Comment by briis** [comment]
The UDP part is running, and is receiving Rapid Wind data and Hub Data, but not the other Tempest data.

@natekspencer Could you have a look at this?

**Comment by natekspencer** [comment]
It looks like your hub is on a newer revision (177) where they dropped the "fs" field on hub status updates. I'll get this patched ASAP

**Comment by briis** [comment]
We just pushed V3.0.1 out. Could you try that and let us know if it fixes your problem. Thanks

**Comment by summitbri** [comment]
Sure will.  I see the update in the repo but not in the HA add-on yet.  Stay tuned...

**Comment by natekspencer** [comment]
> Sure will. I see the update in the repo but not in the HA add-on yet. Stay tuned...

If you click on "Reload" from the Supervisor add-on store, it should find it quicker.

**Comment by summitbri** [comment]
Confirmed this is now working, thanks!
