### ISSUE TITLE
Potential issue with sea level pressure calculation

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#11]
The sea_level_pressure sensor values are not consistent with the Tempest app or with the SmartWeather integration sensor values.  However, the station_pressure is consistently reported in all (for the most part anyway, it is hard to capture a snapshot of everything at exactly the same time).

Tempest app:            29.997 inHg       29.149 inHg
Smartweather:          29.997 inHg       29.149 inHg
weatherflow2mqtt:   29.941 inHg       29.15 inHg

**Comment by GlennGoddard** [comment]
Just as a note there are (3) places where the height above sea level affects things there.
You have the height of your property when the app is installed and then you have the height above ground the weather station is installed (also in app but in a different spot).  These could be in metric or imperial depending on prefs in app.

For the docker container, the height given should be the above two added together and in metric only.

I realize there might still be a calculation problem but if the right numbers are not right then it still won't calculate right.
I will just add that to the PR (the one I will submit for MQTT topic chart) in the documentation to be clearer.

**Comment by briis** [comment]
You are right Glenn - it has to be the sum of the Ground Elevation and the distance from the Ground to the Station.
Anyway, I am not using the exact same formula as Weatherflow does, and that is most likely the reason for the deviation. I will try and convert the formula they use to Python, and that should then solve this issue.

**Comment by GlennGoddard** [comment]
I started making changes and got carried away on the chart...so I will hopefully finish that up in a day or two.
I noticed that WeatherFlow added another option for precip_type with '3' for both rain and hail.

**Comment by briis** [comment]
I have rewritten the formula, and it is now using the same formula as WeatherFlow does. For me it shows correct Sea Level pressure.

New image posted.

**Comment by briis** [comment]
> I noticed that WeatherFlow added another option for precip_type with '3' for both rain and hail.

Yes, this was based on my input. The value here is a binary field so basically 3 is Hail + Rain. In reality this is very rarely Rain and Hail, it is Heavy Rain, so that is what I called it 😬

**Comment by chasut** [comment]
Spot on!  btw, I am always amazed at the level of precision that a barometer provides.  The resolution of the change of air pressure in less than a foot from a tiny sensor.
Thank you.
