### ISSUE TITLE
HA log errors

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#117]
Logger: homeassistant.components.mqtt.sensor
Source: components/mqtt/sensor.py:207
Integration: MQTT (documentation, issues)
First occurred: 5:33:19 AM (26 occurrences)
Last logged: 5:58:17 AM

Invalid state message '{"status": 2139282, "absolute_humidity": 16.82, "air_density": 0.07563, "air_temperature": 69.0, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Gentle breeze", "beaufort": 3, "delta_t": 1.4, "dewpoint": 67.0, "dewpoint_description": "Uncomfortable", "feelslike": 66.6, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 101, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.55, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.77, "rain_yesterday": 0.0, "relative_humidity": 93.28, "sealevel_pressure": 30.164, "solar_radiation": 0, "station_pressure": 30.164, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 12, "wind_bearing_avg": 12, "wind_direction": 12, "wind_direction_avg": "NNE", "wind_gust": 15.9, "wind_lull": 7.58, "wind_speed": 11.72, "wind_speed_avg": 11.72, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'
Invalid state message '{"status": 2139342, "absolute_humidity": 16.86, "air_density": 0.07563, "air_temperature": 69.1, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Moderate breeze", "beaufort": 4, "delta_t": 1.4, "dewpoint": 67.1, "dewpoint_description": "Uncomfortable", "feelslike": 74.0, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 102, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.59, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.78, "rain_yesterday": 0.0, "relative_humidity": 93.3, "sealevel_pressure": 30.164, "solar_radiation": 0, "station_pressure": 30.164, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 5, "wind_bearing_avg": 5, "wind_direction": 5, "wind_direction_avg": "N", "wind_gust": 27.4, "wind_lull": 2.86, "wind_speed": 14.41, "wind_speed_avg": 14.41, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'
Invalid state message '{"status": 2139402, "absolute_humidity": 16.86, "air_density": 0.07563, "air_temperature": 69.1, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Gentle breeze", "beaufort": 3, "delta_t": 1.4, "dewpoint": 67.1, "dewpoint_description": "Uncomfortable", "feelslike": null, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 103, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.51, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.79, "rain_yesterday": 0.0, "relative_humidity": 93.32, "sealevel_pressure": 30.165, "solar_radiation": 0, "station_pressure": 30.165, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 59, "wind_bearing_avg": 59, "wind_direction": 59, "wind_direction_avg": "ENE", "wind_gust": 14.0, "wind_lull": 3.31, "wind_speed": 8.72, "wind_speed_avg": 8.72, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'
Invalid state message '{"status": 2139462, "absolute_humidity": 16.86, "air_density": 0.07563, "air_temperature": 69.1, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Light breeze", "beaufort": 2, "delta_t": 1.4, "dewpoint": 67.1, "dewpoint_description": "Uncomfortable", "feelslike": 69.7, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 104, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.57, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.8, "rain_yesterday": 0.0, "relative_humidity": 93.31, "sealevel_pressure": 30.165, "solar_radiation": 0, "station_pressure": 30.165, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 44, "wind_bearing_avg": 44, "wind_direction": 44, "wind_direction_avg": "NE", "wind_gust": 12.57, "wind_lull": 2.73, "wind_speed": 7.18, "wind_speed_avg": 7.18, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'
Invalid state message '{"status": 2139522, "absolute_humidity": 16.87, "air_density": 0.07563, "air_temperature": 69.1, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Light breeze", "beaufort": 2, "delta_t": 1.4, "dewpoint": 67.1, "dewpoint_description": "Uncomfortable", "feelslike": 70.0, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 105, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.54, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.81, "rain_yesterday": 0.0, "relative_humidity": 93.3, "sealevel_pressure": 30.165, "solar_radiation": 0, "station_pressure": 30.165, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 61, "wind_bearing_avg": 61, "wind_direction": 61, "wind_direction_avg": "ENE", "wind_gust": 11.41, "wind_lull": 3.13, "wind_speed": 6.76, "wind_speed_avg": 6.76, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'

**Comment by robertw** [comment]
I have uninstalled and reinstalled mqtt and the add on on a clean install of ha and still have the same error

of 300 of them filling my log file I also removed the forcat flag and replaced it no change any gudiance would be helpfull thank you.

 Invalid state message '{"status": 2139282, "absolute_humidity": 16.82, "air_density": 0.07563, "air_temperature": 69.0, "battery": 2.4, "battery_level": 59, "battery_mode_description": "Wind sampling interval set to 6 seconds", "battery_mode": 1, "beaufort_description": "Gentle breeze", "beaufort": 3, "delta_t": 1.4, "dewpoint": 67.0, "dewpoint_description": "Uncomfortable", "feelslike": 66.6, "illuminance": 0, "lightning_strike_count": 0, "lightning_strike_count_1hr": 0, "lightning_strike_count_3hr": 0, "lightning_strike_count_today": 0, "lightning_strike_distance": 0, "lightning_strike_energy": 0, "lightning_strike_time": "unknown", "precipitation_type": "Rain", "rain_duration_today": 101, "rain_duration_yesterday": 0, "rain_intensity": "Heavy", "rain_rate": 0.55, "rain_start_time": "2021-12-13T09:00:02+00:00", "rain_today": 0.77, "rain_yesterday": 0.0, "relative_humidity": 93.28, "sealevel_pressure": 30.164, "solar_radiation": 0, "station_pressure": 30.164, "temperature_description": "Nice", "uv": 0.0, "uv_description": "None", "visibility": 0.1, "wbgt": 65.8, "wetbulb": 67.7, "wind_bearing": 12, "wind_bearing_avg": 12, "wind_direction": 12, "wind_direction_avg": "NNE", "wind_gust": 15.9, "wind_lull": 7.58, "wind_speed": 11.72, "wind_speed_avg": 11.72, "pressure_trend": "Steady", "pressure_trend_value": 0, "last_reset_midnight": "2021-12-13T05:00:00+00:00"}' from 'homeassistant/sensor/weatherflow2mqtt_ST-00051410/observation/state'

**Comment by briis** [comment]
This is really strange. The data above looks as it should, comparing to what I have in the same topic. I have no errors in my log and all sensors are updating.

- Could you try and stop the Add-On or The Docker container (Depending on how you have set it up)
- Then go to Home Assistant and Integrations.
- Find the MQTT Integration and click on `x Devices`
- Now find devices that start with either `Hub`, `Tempest` or `WeatherFlow`.
- Click on each of them  and then click Delete

Now all sensors should be out of your system. You could, just to be sure, also click on Entities in the MQTT Integration and see if you have any old obsolete entities floating around, and then delete them too.

Now Start the Add-On or Container again. It can take a little time before it shows up in MQTT, but you should have 2 Devices for your Tempest setup. 

If you still have issues, please give me your Station Id and I will try and look at the Raw data that is also send to WeatherFlow.

**Comment by robertw** [comment]
I did a full remove and reinstall of both mq and tempest and cleared database files and all other entitles 
62439
is the id thanks oh yes still have the same log warning

**Comment by briis** [comment]
I am puzzled. I am just getting 'Not Found' message when trying to see the data on WeatherFlows site. 

Is your station Public? If not, could you make it public. It does not have anything to do with your internal setup, and just makes it possible for other people to see the weather at your location.

**Comment by briis** [comment]
@natekspencer Do you have an idea on what is going on here?

**Comment by robertw** [comment]
Done sorry

**Comment by briis** [comment]
I want to be where you are - you have nice weather 😁

All your data looks exactly right, and if I use this Integration https://github.com/briis/hass-weatherflow which uses the REST API, then all data is retrieved and working fine. 

I have asked @natekspencer to look at this also, he did the re-write of the engine, to see if he can figure out why it is not working. In the meantime you can use the REST Api as described above - instructions are on the Github.

**Comment by robertw** [comment]
Many thanks yeah the weather is kind of nice isn't it you're welcome to
visit anytime you like.

Continue utilizing the home assistant and just let the log fill and Purge
it every once in awhile I also tried it from an external docker container
just to see if it was an internal problem it is not

**Comment by natekspencer** [comment]
Looks like it was introduced in 2021.12 release of HA for datetime conversion: https://github.com/home-assistant/core/commit/5c443b626ad7513794093ab482ddc404b75ca1b7#diff-e1bfac306252836d15acf78b96786db37a7011f111a795e3571fe65afb4621abR207

**Comment by briis** [comment]
@robertw We have just released V3.0.3, which should fix your issue. Could you test it out and report back. Thanks

**Comment by robertw** [comment]
Looking like the update resolved the matter thank you
