### ISSUE TITLE
Forecast not updating

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#119]
I just noticed that the forecast data is not updating.  Today is Wed and my forecast is showing Mon-Fri.  Current conditions appears to be updating however.

**Comment by GlennGoddard** [comment]
Just updated WF and HA at the issue resolved both had new images today; so I can't say which it was but it is on Wed now.

**Comment by briis** [comment]
Always tricky when things fix themselves 😁
I pushed a new image to the `dev` tag, that will eventually be 3.0.4. Here there is better debugging options for this situation. Should it start again, please enable debug, and re-open this issue with the results.

**Comment by GlennGoddard** [comment]
Well.....
I should have learned this by now, but updating containers right before I go to bed never seems to go well, yet I still keep doing it.
When I get back home I will enable debugging, but I updated to the latest dev build yesterday and now I only get forecast and nothing else.  From the initial look, it appears that very little is getting to MQTT.

More to follow when I get a chance to debug.

**Comment by GlennGoddard** [comment]
I don't know if this is limited to me but forecast and current conditions only updates on container restart and then never updates again.   All other functions appear to work.  Nothing obvious in logs (posted in other closed issue)

**Comment by briis** [comment]
I don't experience this with the latest 3.0.5 release. Forecast data updates as expected.
