### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#124]
Failed to install add-on
Can't install briis/weatherflow2mqtt:3.0.4: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=3.0.4&fromImage=briis%2Fweatherflow2mqtt: Not Found ("manifest for briis/weatherflow2mqtt:3.0.4 not found: manifest unknown: manifest unknown")

**Comment by briis** [comment]
This is actually not released yet. But I found out that the Add-On is looking in CHANGELOG to see if there is a new version, and as that was updated, the Add-On also thinks it updated. Please ignore the update for now.

**Comment by robertw** [comment]
Ok thanks will close
