### ISSUE TITLE
large docker container

### ISSUE THREAD

**Issue by leonardpitzu** [briis/hass-weatherflow2mqtt#125]
Currently the `python:3.9-buster` is used which results in a quite large container given the functionality. Why not use `python:3.9-slim-buster`. I personally have tried it and have not seen any problems so far.
Also Alpine Linux would do it as their base container is very small.

**Comment by briis** [comment]
What platform are you running on? 
I do think I tried it early in the development phase, but I missed some libraries on the Arm platform if I remember right. But it might be a good time to try again.

**Comment by leonardpitzu** [comment]
x86 Intel (synology and generic computer).
Maybe somebody with ARM/ARM64 can try it and report back so we can know for sure.

**Comment by briis** [comment]
I have a function to build on all platforms, so they will complain if something is missing. I will give a try a bit later.

**Comment by briis** [comment]
Just tried to build the containers with `slim-buster`. And the Arm containers failed building. 
I will spend a little time looking at a fix for the failed build, but else revert back to the full version.

**Comment by briis** [comment]
Ok, I think I found what was missing - it was a C++ compiler to build some of the wheels.
I have now successfully build for all 3 platforms, and now comes the exciting times - test if it works.

Could you try and pull `briis/weatherflow2mqtt:dev` and test if that works?

Image size is down 140Mb vs 336 Mb with the full Buster version.

**Comment by leonardpitzu** [comment]
Works great, thanks, but somebody please take a look at ARM/ARM64.

**Comment by briis** [comment]
I can add that to the builder

**Comment by GlennGoddard** [comment]
This dev version works for me at the moment

**Comment by briis** [comment]
> Works great, thanks, but somebody please take a look at ARM/ARM64.

Just read this again, and I am already building for that platform, so I guess you meant someone should test it😁
What HW is typical using that? I have a lot of different boxes, so I might actually be able to test it myself.

**Comment by leonardpitzu** [comment]
Yes, that's what i meant - somebody should test it.
If you have a raspberry pi you can give it a spin. The pi4 is actually ARM64 but the OS (raspbian) is just 32bit... Maybe pi4+armbian (don't know if they have a 64bit release for the thing yet).

**Comment by briis** [comment]
I have a PI4 lying around somewhere. I will see if I can find a 64Bit operating system to load on that.

**Comment by briis** [comment]
This seems to work for all now, so I will close the issue. Thanks for the hint.
