### ISSUE TITLE
no data after some time

### ISSUE THREAD

**Issue by leonardpitzu** [briis/hass-weatherflow2mqtt#126]
I have a strange issue - after some time (about 10-12 hours) i see no more data being pushed in HA. I am trying to catch it in the logs but until now I could not do it. Any hint as to what can happen? This is an issue after the 3.0.2/3.0.3 update from what i can see.

**Comment by briis** [comment]
Duplicate of #121

**Comment by leonardpitzu** [comment]
mea culpa - didn't see it

**Comment by GlennGoddard** [comment]
@leonardpitzu I would close this issue since it is merged with the other.

**Comment by leonardpitzu** [comment]
Sure, please do so.

**Comment by GlennGoddard** [comment]
I meant that you could close this since you were the auther.

**Comment by leonardpitzu** [comment]
Overlap with #121
