### ISSUE TITLE
On Home Assistant,  "WF Feels Like Temperature" drops to 0.

### ISSUE THREAD

**Issue by cmsimike** [briis/hass-weatherflow2mqtt#127]
I keep seeing instances of WF Feels Like Temperature dropping to 0 (see attached)
![image](https://user-images.githubusercontent.com/204378/146991311-c19f1ee1-1194-4258-a1b6-cb0d63c9ae96.png)

However the temperature sensor is fine:

![image](https://user-images.githubusercontent.com/204378/146991360-52625710-5803-42e4-8d1f-fbf6115295c7.png)

Any thoughts?

**Comment by natekspencer** [comment]
This should get resolved with 3.0.4 when it is released

**Comment by briis** [comment]
3.0.4 is now released. Please let us know if this fixed it.

**Comment by briis** [comment]
Assume this is now fixed. Please reopen if that is not the case.
