### ISSUE TITLE
Add Cloud Base

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#130]
### New Feature

Determine altitude of clouds above sea level.  This is one of the prerequisites for local current conditions.

Simplified with all metric units:
CloudBase (in meters AMSL = {ground temperature (C) - dewpoint (C) }* 126 + station height (in meters)

AMSL or MSL (Above Mean Sea Level) altitude above sea level
AGL (Absolute Ground Level) altitude above ground level [added for information]

**Comment by GlennGoddard** [comment]
This formula is a common way for pilots to calculate the cloud altitude since some pilots are required to maintain 500 ft below cloud level.  Since it is hard to maintain an altitude of 500 ft less that the clouds if you don't know what level the clouds are at.

Again just like Freezing Line this is a simplification but this is a commonly used method from my research.  I have found aviation based web sites very useful for information on snow and clouds.

**Comment by natekspencer** [comment]
I found this that matched your formula: https://holfuy.com/en/support/cloud-base-calculations

**Comment by GlennGoddard** [comment]
How is the progress going to revamping the integration?
I am waiting to do any PRs for additional sensors until you have it in stable branch just so there aren't too many changes at the same time.

**Comment by natekspencer** [comment]
@GlennGoddard, when you get a chance, can you take a look at https://github.com/briis/pyweatherflowudp/pull/12 and let me know if the calculations look correct?

**Comment by GlennGoddard** [comment]
Cloud Base looks good
Freezing Level looks good.

Wow, you went thru and changed all sea level to mean sea level in the descriptions...overkill...correct, but overkill since sea level is assumed to be the mean sea level.  I'm impressed.  I also noticed the station height to altitude change.

I didn't realize we were moving the functions also, but I guess that is best so other groups that don't use this integration will also benefit.

i assume that recording the hi/lo and the MQTT functions are all that need to be done here now???

I don't follow the "# check calculated metrics requiring extra parameters" section but I didn't look at the full code just the changes.  I'm guessing error control for now.

You are too quick, I was planning on doing this...but here, so it would have need to be moved anyway.
I'll have to review this later to see if you got all the other calculated sensors and tweaking the visibility function.   I just need more days with <90% humidity to test.  I think I got it working fairly well but I want to incorporate the effect of rain rate on visibility also.

**Comment by natekspencer** [comment]
> I didn't realize we were moving the functions also, but I guess that is best so other groups that don't use this integration will also benefit.

Yeah, the plan (in my mind anyway), is to have the sensor communication and point-in-time attribute level calculations provided by the pyweatherflowudp module. @briis and I briefly chatted this morning and decided that the module should include the two new functions you were requesting.

> i assume that recording the hi/lo and the MQTT functions are all that need to be done here now???

Correct, this will still be done in the hass-weatherflow2mqtt project (and others) as they require historical data that the pyweatherflowudp module will not include as part of its functionality. This way the consumers can decide how best they want to store data but get a consistent set of calculations and attributes from the sensors. Certain other calculations, like the Zembretti Algorithm you are also requesting, will also likely be done in hass-weatherflow2mqtt since it relies on historical data.

> I don't follow the "# check calculated metrics requiring extra parameters" section but I didn't look at the full code just the changes. I'm guessing error control for now.

That's just a note in the testing files and a way to visually separate the attributes from the methods. Because cloud base, freezing level, and sea level pressure all require an altitude (which can't be retrieved from the UDP data), they are implemented as methods instead of properties. I've got the pyweatherflowudp package at 100% code coverage, that way I can try to ensure future changes don't break unless I'm making a conscientious decision to do so, in which case the tests would be updated accordingly.

**Comment by natekspencer** [comment]
> Certain other calculations, like the Zembretti Algorithm you are also requesting, will also likely be done in hass-weatherflow2mqtt since it relies on historical data.

Actually, the formula for this might make sense to include in the calcs.py file in pyweatherflowudp, but other projects would have to specifically call it with the historical data to get the results.

**Comment by briis** [comment]
Just pushed a new build to the `dev` tag, which contains these two sensors. Could you test it out?

**Comment by GlennGoddard** [comment]
I will test when I get back home, it will be a few hours (maybe 12ish) from now.

**Comment by GlennGoddard** [comment]
Icon recommendations for Cloud Base
mdi:cloud
mdi:cloud-outline
mdi:cloud-upload
mdi:weather-cloudy

I am leaning towards mdi:weather-cloudy

Posting here to get input instead of just doing the PR myself.

**Comment by natekspencer** [comment]
> Icon recommendations for Cloud Base mdi:cloud mdi:cloud-outline mdi:cloud-upload mdi:weather-cloudy
> 
> I am leaning towards mdi:weather-cloudy
> 
> Posting here to get input instead of just doing the PR myself.

I actually already did it, haha: https://github.com/briis/hass-weatherflow2mqtt/pull/135

**Comment by GlennGoddard** [comment]
Then I probably should not waste my time on freezing level or are you still looking for icons?

**Comment by natekspencer** [comment]
> Then I probably should not waste my time on freezing level or are you still looking for icons?

I chose altimeter for it, but I could be swayed as well.

**Comment by GlennGoddard** [comment]
Nevermind, I see the altimeter.  Well, nevermind the nevermind, you responded

**Comment by GlennGoddard** [comment]
Altimeter is probably the best since mdi:cube-outline is the next best I can come up with.
Maybe mdi:snowflake or mdi:snowflake-variant but altimeter for now; if I don't like it I can always change it in my setup.

**Comment by natekspencer** [comment]
Yeah, I ended back on altimeter after looking at snowflake as well. It didn't feel quite right, so altimeter still seemed more appropriate.

**Comment by GlennGoddard** [comment]
I agree; I think a recent HA update added more icon libraries.  I need to look to see if that is the case.

**Comment by GlennGoddard** [comment]
Just documenting here for my future reference to see about cloud base adjustments:
December 23, 2021:
WF Cloud Base: 764ft
Actual Cloud Base: Between 1400 and 1900ft

This actually is not that bad for an estimation.  Seems like a big difference because it is so low.  I 'conveniently' have a major airport not far away so getting actual cloud level is easy.
[https://www.weather.gov/zse/PIREPClouds?id=SEA&hrs=24](https://www.weather.gov/zse/PIREPClouds?id=SEA&hrs=24)
I will observe over different weather conditions and times of year.  I personally will not be able to check in different locations however.  Once this hits stable, I will post in WF forums for other observations.

**Comment by GlennGoddard** [comment]
I think you chose right with the altimeter.  It stands out and it looks good.
