### ISSUE TITLE
Add Freezing Line / Snow Line

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#131]
### New Feature

SnowLine = (192 * AirTemperature) + StationElevation
where:
SnowLine is altitude above sea level where snow is possible in meters
AirTemperature is station temperature in C
StationElevation is altitude of station above sea level in meters

In this case SnowLine is also the FreezingLine (I'm ok with either term, but freezing line is probably the most accurate since snow line is the the altitude above which snow is possible)

Snow Line and Cloud Base will be used in the snow probability for current conditions (local)

**Comment by natekspencer** [comment]
Can you also share where these formulas are derived from?

**Comment by GlennGoddard** [comment]
There is some simplification and averaging here.

Freezing Line is where temperature is temperature is 0C.
Air Temperature is measured at Station Elevation.

DALR (Dry Adiabatic Lapse Rate) is the rate at which temperature drops with raise in altitude (in dry air), this varies with latitude and atmospheric pressure.

SALR (Saturated [or wet] Adiabatic Lapse Rate) is the temperature drop for raise in altitude in very humid air.  There are varieties of formulas for this also; one being: SALR = 6.25 - 2 *[sin(latitude)]

There are many different assumptions for this, I went with an 'fairly' used average of 1C drop for every 192 meters in altitude for simplicity and this is a common assumption for pilots for flight plans.

I may have more info in both the discussion section here for new sensors (where @briis suggested I make a separate issue for each sensor) and the issue for local weather conditions.

I am by no means a weather expert and realize that this is a generalized formula, but I am keeping all calculations to variables that can be locally obtained from the weather station data.  There may be some fine tuning but it is a start.

Humidity changes with altitude so the lapse rate will always be a combination of DALR and SALR but we can only measure at ground level and make assumptions or generalizations.

Also typically the actual altitude where snow could fall is + or - 500 ft (100ish meters) of the actual 0C altitude.

Here is part of the discussion:
[https://community.home-assistant.io/t/local-offline-self-hosted-weather-forecast/349135/16](https://community.home-assistant.io/t/local-offline-self-hosted-weather-forecast/349135/16)

**Comment by natekspencer** [comment]
Thanks, that's super helpful. Some of it I just want to know for myself, but also be able to explain it.

**Comment by GlennGoddard** [comment]
It would be useful to have latitude as an input not just here but for other things like being able to calculate sun angle to get a good UV estimate for the day of year and time of day to be able to determine if cloudy.  For now I am working with what is currently available in the integration.  Maybe sometime in the future we can add latitude as a docker variable, but this will probably be a breaking change unless there is a default given.

The plan for Freezing Line and Cloud Base is to be able to determine a probability of snow; which could be a sensor in and of itself but mainly my first case use was for the local calculation of current conditions.

**Comment by GlennGoddard** [comment]
Probably need to add bottom cutoff at 0ft/0m for freezing line.  Didn't think of it before, but it is 30F here and -371ft freezing line; which is right but it 99% of the cases sea level should be the bottom.

**Comment by badewanne1234** [comment]
It spring here and I only recently got my Temptest - may I ask: what is reported when it is snowing at this stage: rain or none/nothing?

**Comment by badewanne1234** [comment]
Thanks, I understand that.  But is snow currently reported as rain or as no precipitation?

**Comment by natekspencer** [comment]
> Thanks, I understand that. But is snow currently reported as rain or as no precipitation?

The answer is: it depends. If it's strong enough (blizzard, high winds or other) to trigger the haptic sensor, then it will show as rain (or possibly hail or rain/hail). If not, it will show as no precipitation.

**Comment by badewanne1234** [comment]
Thank you! 👍🏻
