### ISSUE TITLE
Weather forecast stops updating after some time has passed

### ISSUE THREAD

**Issue by natekspencer** [briis/hass-weatherflow2mqtt#137]
Scratch that 'all good'.  My weather forecast stopped updating yesterday.
Logs to follow.
[wf.zip](https://github.com/briis/hass-weatherflow2mqtt/files/7777364/wf.zip)

Restarting the container updated the forecast.   Log says it was sending forecast data to MQTT but it was not.   Might need more debugging around forecast.  I don't know if it was not fetching the data or if it was not sending it on.

_Originally posted by @GlennGoddard in https://github.com/briis/hass-weatherflow2mqtt/issues/121#issuecomment-1001222199_

**Comment by GlennGoddard** [comment]
Ok, looks like it updates during the day it is restarted but fails around midnight.

**Comment by natekspencer** [comment]
Yeah, I was able to find the issue and is documented in #138 now.

**Comment by briis** [comment]
@natekspencer made a fix for this, and I pushed a new `dev` container. Could you test this @GlennGoddard and see if this is stable?

**Comment by GlennGoddard** [comment]
Got the latest build.  I will let you know tomorrow if it worked.

**Comment by GlennGoddard** [comment]
Everything appears to be working with a full day of testing.

**Comment by briis** [comment]
3.0.6 is now released. Thanks.
