### ISSUE TITLE
Beaufort Scale is not displayed in Battery Mode 3

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#139]
### Home Assistant Version?

2021.12.3

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

Latest Dev build

### What happened?

When Tempest is in Battery Operating mode 3 only Wind speed, Wind Direction, Wind Bearing is displayed.  No avg, gust, or lull is sent from Tempest.  Beaufort scale is not calculated (shown as None).

I have not had a chance to review the code to see but I suspect that the Beaufort scale pulls from Average.
The Tempest documentation only states that wind reading frequency is reduced; this is not entirely true.  I have not got any average (speed or direction), gust or lull readings in over 18 hours.

This is my first experience with mode 3 so this is all new information.  I have posted in WF forum, I probably need to add that the documentation needs to be updated to clarify what is reported.

Just to note that the haptic sensor also does not report any data (this is correctly documented).
It does appear the Wind Speed is updated every 5 minuets.

Also not that the new issues template requires something be typed in by user in each block (even if it is already filled out like the HA version); this took me some time to figure out since there was something displayed in each box.  I would recommend not having defaults pre-filled-in if it still has to be typed by user.

### Relevant log output

```shell
Not available from current location at this time; can submit when I get home if needed.
```

**Comment by briis** [comment]
Thanks for reporting this Glenn. I fortunately have had the odd day with Sunshine, and managing to keep the Tempest at 0 to 1 battery mode. (One day with 2).

> I suspect that the Beaufort scale pulls from Average

That is correct. So the Wind Speed from the Rapid Wind Event seems to update, is that what you see? We could then maybe use that value if battery mode is 3

>  requires something be typed in by user in each block

Good point on the Issue Template - I will remove the defaults.

**Comment by GlennGoddard** [comment]
The wind speed and bearing that would previously considered rapid are all that is received for wind.  There have been no outputs for (due to no inputs from WF):
Beaufort scale
Precipitation Type
Rain Intensity
Wind Bearing Avg
Wind Direction Avg
Wind Gust
Wind Lull
Wind Speed Avg

Rain Rate and Rain Today and Rain Duration (both today and yesterday) correctly (given no input) display a "0"; Rain Duration Yesterday shows 809mins (which is accurate until data from Tempest stopped)

When I get home I will make sure I capture the logs since I don't know if I will get back down to level 3.
I know I had to make assumptions for the Battery Mode since we didn't have all the data available; but I might work on some modification to take into account of lack of inputs to display Mode 3.  I've seen that battery voltage fluctuates which causes the calculation to sometimes state Level 2 when the Tempest is actually still in 3 (determined by lack of data).  I am at that thousandth of a volt fluctuation from/to 2.355 and 2.356.

Let me know if there is any other data that might be useful at this time.
There might be other delays in humidity and temperature but that is hard to tell if it is reduced or if they are not actually changing much.  I will see if logs can clarify.
Lightning might have issues:
Lightning Count (3 hr) = 0
Lightning Count = 0
Lightning Count (Last Hour) = 0
Lightning Distance = 0
Lightning Energy = 0
Last Lightning Strike = Unknown

The good news is that the error handling seems to be working perfectly.

**Comment by GlennGoddard** [comment]
Log attached for reference if needed:
[wf.zip](https://github.com/briis/hass-weatherflow2mqtt/files/7832537/wf.zip)

**Comment by GlennGoddard** [comment]
It looks like the function
```
else cnv.beaufort(device.wind_average.m),
```
line 206 in sensor_description.py is what needs to change to:
```
else cnv.beaufort(device.wind_speed.m),
```
based off what I can tell from looking at pyweatherflowudp/mixins.py for wind speed

**Comment by briis** [comment]
With a battery mode of 0 or 1, this would update the Beaufort Value more often, but I just checked a few sites to see if this should be calculated based on average wind or current wind, and there is no mention of that anywhere, so I guess there is nothing wrong with moving it to `wind_speed`

**Comment by GlennGoddard** [comment]
Would it be better in Mode 0 or 1 to use GUST and then in 2 and 3 (>1) use RAPID.  Ideally you want the peak wind speed, so GUST makes more sense.

**Comment by briis** [comment]
I have posted a new `dev` build, that uses `wind_speed` from rapid wind, but falls back to wind_avg if no rapid wind for some reason.

Test it out, and let us know how this goes.

**Comment by GlennGoddard** [comment]
I won't be able to fully test until an unknown date in the future since we also got just enough sun in a day to get me from 3 back to 1 (not quite enough for 0).  I will be able to test for whatever current mode it is thou.

**Comment by briis** [comment]
No problem. We will just leave this open for a while.

**Comment by GlennGoddard** [comment]
There might be a firmware change coming that changes the battery modes.  This is in response to my comment about the current Tempest battery mode documentation as not being completely correct.

"I have already forwarded it internally and it is indeed a bit dubious. Thing is there will soon be another update with the power saving modes that will change several things. For the moment they leave it as is and completely re write the new Power Safe Modes when coming life. For now we don’t annonce it yet as it is not fully definitive and some details can still change like many things, last minute finds.

I don’t have yet the ETA for this but hopefully soon."

**Comment by briis** [comment]
Hi Glenn,
I will close this now. Please reopen next Winther if it is still a problem.

**Comment by GlennGoddard** [comment]
WeatherFlow update the documentation for Battery Mode and it just clarifies that ALL wind is affected by the reduced operating modes.

The 'info' button next to battery brings up the documentation.  I don't remember seeing it there and it may only show up in "Power Save" modes; I just happen to have drop to 2 an hour ago.     Everything does appear to function still.

**Comment by GlennGoddard** [comment]
I need to gather more data but in Mode 3 there is no:
Beaufort Scale
Wind Bearing Avg
Wind Direction Avg
Wind Gust
Wind Lull
Wind Speed Avg
Zambretti Number
Zambretti Text
No Lightning or rain detection

I will open a new issue but just documenting while I have the info.

Still get:
Wind Direction
Wind Speed

Only been in mode 3 for an hour; so I'm not sure what other calculations are affected yet.
