### ISSUE TITLE
Odd behavior of forecast on HA mac

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#14]
Ok, to begin with, I am not sure if this is an issue, a feature request, or just a plea for help.

On the HomeAssistant app for Mac, when the hourly forecast is presented it is offset by -5:00 hours.  This only happens on the HA Mac app, not in safari, chrome, or the HA companion app on iOS or iPadOS.  I am not sure when this started, but no matter what I try, it does not change. I have cleared, reloaded, reset, and re-installed, always the same result.  However, if I switch to the rest sensors (SmartWeather integration) it works as expected.

The offset is as if it believes it is receiving a UTC date, and then converting to local time.  (see attached screenshots)

The reason I am posting is that the only thing I can see that is different is how the time is represented in the forecast.  e.g. the hourly forecast from weatherflow2mqtt represents the date string as '2021-06-10T11:00:00' whereas SmartWeather (and other weather entities) include the tz offset '2021-06-10T17:00:00+00:00'.  I am not sure if this difference should even matter, nor do I understand why the translation is occurring only on the Mac application.  But I can consistently reproduce the problem.

thoughts?  TIA

The first two are from Safari browser, the second two are from the HA Companion Mac app.  

![Screen Shot 2021-06-10 at 10 54 33 AM](https://user-images.githubusercontent.com/42701104/121559308-16f3da00-c9dc-11eb-91e3-652032a711f5.png)
![Screen Shot 2021-06-10 at 10 55 13 AM](https://user-images.githubusercontent.com/42701104/121559318-19eeca80-c9dc-11eb-8183-e0b9a77e1895.png)
![Screen Shot 2021-06-10 at 10 50 21 AM](https://user-images.githubusercontent.com/42701104/121559328-1d825180-c9dc-11eb-9a6f-04919a96d595.png)
![Screen Shot 2021-06-10 at 10 50 50 AM](https://user-images.githubusercontent.com/42701104/121559338-1f4c1500-c9dc-11eb-90a9-cfdd5a920808.png)

**Comment by briis** [comment]
It works perfectly for me on all types of devices and Apps, also the Companion APP on my Mac. The date is formatted as an ISO date and that should normally do it, but I can try to get the timezone added also.

**Comment by briis** [comment]
I have now pushed a new release that converts and displays all datetimes in UTC format. Please test this out, and let me know if it is accurate.

**Comment by chasut** [comment]
Looks great on my end.  All clients and forecast variants show correctly.  

Many, many thanks.
