### ISSUE TITLE
Battery mode not present, causing warnings

### ISSUE THREAD

**Issue by zacs** [briis/hass-weatherflow2mqtt#140]
### Home Assistant Version?

2021.11.5

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

3.0.6

### What happened?

For whatever reason, there is no battery mode on my Air or Sky, which causes the following warning to fire. 

![image](https://user-images.githubusercontent.com/27705/148833943-1794d654-19fb-4e9f-b261-2d575bd59567.png)

![image](https://user-images.githubusercontent.com/27705/148834041-b2802eff-b8a7-4741-8dee-163be17fb8f8.png)

### Relevant log output

```shell
Logger: homeassistant.helpers.template
Source: helpers/template.py:1706 
First occurred: 12:01:34 (80 occurrences) 
Last logged: 12:19:45

Template variable warning: 'dict object' has no attribute 'battery_mode_description' when rendering '{"attribution": "Powered by WeatherFlow2MQTT", "description": "{{ value_json.battery_mode_description }}"}'
Template variable warning: 'dict object' has no attribute 'battery_mode' when rendering '{{ value_json.battery_mode }}'
```

**Comment by GlennGoddard** [comment]
@briis It looks like the MQTT message format for discovery is sent but not the message (which is correct).
I don't think it is a 'problem' pe se but it can make the logs cluttered.

**Comment by GlennGoddard** [comment]
@zacs Only the Tempest has battery mode as assigned by WeatherFlow.  There is no reason we can't just assign an arbitrary value but we probably need to remove that from auto discovery so it just doesn't log any thing for not being there in your logs.

Do you have a Tempest and a Sky and Air?  or just an Air & Sky

**Comment by natekspencer** [comment]
> Only Sky/Air. Agree I was surprised by the mode since I'd not heard of it, but seems it would need to be removed (conditionally) from the attribution string as well.

Looks like I was properly excluding it from the updates, but not from the initial sensor creation. I've adjusted that now in #141

**Comment by briis** [comment]
The fix is in the latest `dev` tag build, which is available now.

**Comment by zacs** [comment]
Just pulled from `dev` and restarted the container. Had to manually delete the `battery_mode` sensors from the MQTT broker but the warning no longer fires. Thanks for the fast fix!
