### ISSUE TITLE
Daily low broken after negative temp

### ISSUE THREAD

**Issue by summitbri** [briis/hass-weatherflow2mqtt#144]
### Home Assistant Version?

2022.02

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

latest

### What happened?

![image](https://user-images.githubusercontent.com/36425892/155031075-b63ad1b0-eafb-4593-99ef-e456b1dbf108.png)

Daily low temp seemingly stops reporting after negative temperatures reported.

### Relevant log output

```shell
Tempest ST-00050852 Temperature
37.3	state_class: measurement
attribution: Powered by WeatherFlow2MQTT
max_day: 38.7
max_day_time: 2022-02-21T17:31:32+00:00
max_month: 48.6
max_month_time: 2022-02-15T22:21:49+00:00
max_all: 50.7
max_all_time: 2022-01-07T22:24:40+00:00
min_day: 0.0
min_day_time: 2022-02-04T11:50:30+00:00
min_month: -12.1
min_month_time: 2022-02-03T09:44:54+00:00
min_all: -12.1
min_all_time: 2022-02-03T09:44:54+00:00
unit_of_measurement: °F
device_class: temperature
friendly_name: Tempest ST-00050852 Temperature
```

**Comment by summitbri** [comment]
Here's a better chart 
![image](https://user-images.githubusercontent.com/36425892/155031746-e3ad32cc-bcfc-4ae6-a567-15a84cc71a9a.png)

**Comment by briis** [comment]
Strange issue. All fields in the database are floating points, so they are capable of handling negative values. And in my own database I have several negative values. 
To ensure it is not something with the charting program, could you check what it is the actual MQTT attribute values. It is found in the MQTT topic: `homeassistant/sensor/weatherflow2mqtt_YOURDEVICENAME/high_low/attributes`

**Comment by summitbri** [comment]
Hi there, same result in the MQTT values:

 "air_temperature": {
    "max_day": 24.1,
    "max_day_time": "2022-02-22T07:01:12+00:00",
    "max_month": 48.6,
    "max_month_time": "2022-02-15T22:21:49+00:00",
    "max_all": 50.7,
    "max_all_time": "2022-01-07T22:24:40+00:00",
    "min_day": 0,
    "min_day_time": "2022-02-04T11:50:30+00:00",
    "min_month": -12.1,
    "min_month_time": "2022-02-03T09:44:54+00:00",
    "min_all": -12.1,
    "min_all_time": "2022-02-03T09:44:54+00:00"
 },

**Comment by briis** [comment]
Something might be wrong with the day min temp in the database, since it stays on 0. Is there anything showing up in the log files? If not the only suggestion I have is to stop the docker container, delete the `weatherflow2mqtt.db` and restart. This will create an empty database. Or if you can, open the database, and see if there is a bad value in the fields.

**Comment by summitbri** [comment]
Update, I deleted the database and daily low is working again.  I'll re-open this issue if it happens again.
