### ISSUE TITLE
 Lightning Count history graph is shown as bar(?) chart instead of a line

### ISSUE THREAD

**Issue by Vitani** [briis/hass-weatherflow2mqtt#148]
### Home Assistant Version?

2022.5.5

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.0.7

### What happened?

`Count`, `Count (3 hours)` and `Count (1 hour)` all show as a bar(?) chart
![image](https://user-images.githubusercontent.com/5907401/169260293-e18c18e6-4733-4a8a-a901-7a0b94ecd30b.png)
![image](https://user-images.githubusercontent.com/5907401/169260353-6759ca44-ddc9-4095-a5d7-1c10354172fc.png)
![image](https://user-images.githubusercontent.com/5907401/169260403-864abcb0-d429-4d75-9f00-62cb50eb91a3.png)

`Count (Today)` works as expected -
![image](https://user-images.githubusercontent.com/5907401/169260467-7338b904-4c7d-45b8-8a04-33023fe47198.png)

**Comment by GlennGoddard** [comment]
All I can say for this is: sometimes this happens in HA.  It may take the period of time you have your database before the purge.  Mine is 14 days.  If any issue happen any any 'string' was received it can throw off the history graph; the way I get around this is I use the custom:mini graph card with will ignore all strings and always give you a graph.  Plus the mini graph has more options for you to play with.

**Comment by briis** [comment]
The Internal Database is not stable enough, and will be deprecated sometime in the future. I would recommend that you look at the Long Term Stats as @GlennGoddard also points out.
