### ISSUE TITLE
 Lightning data does not match what's in the Tempest app

### ISSUE THREAD

**Issue by Vitani** [briis/hass-weatherflow2mqtt#149]
### Home Assistant Version?

2022.5.5

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.0.7

### What happened?

Tempest app shows 3 lightning strikes in the past three days, all last night
![image](https://user-images.githubusercontent.com/5907401/169259707-fcc26891-144b-4631-a4e8-5589893e0557.png)
But the integration show hundreds
![image](https://user-images.githubusercontent.com/5907401/169259949-174b0ed1-3ae7-4edf-af76-8425d7f262a4.png)

**Comment by GlennGoddard** [comment]
This is as expected.  WeatherFlow filters out lightning on their side by determining if 'nearby' stations record lightning or not.  If no other station records lightning then your stations lightning is discarded and will not display in the app.  The local integration here has no ability to compare with others, so all data is displayed.

**Comment by GlennGoddard** [comment]
It looks like you might have the same issue I did last year.  I was getting a recorded strike every couple of minutes.  I moved my station a few feet in one direction and eliminated the false lightning.

The Franklin sensor will pick up arcing of electrical components, so that is something to keep in mind.  Relays, motors, radio transmitters, spark plugs could all be possibly picked up.  On the 17th, was there some piece of equipment not in use by you or your neighbors?

**Comment by Vitani** [comment]
Thanks for the tips, I can't think of anything that's been different on the 16/17/18th, but now I know I'll pay more attention to it. In the `Lightning Energy` sensor, I get a constant "hum" of energy, and a few large spikes (none of which match up with the strikes reported by the Tempest app), so there could well be something leaking electrical energy nearby. Thank-you @GlennGoddard !

![image](https://user-images.githubusercontent.com/5907401/169305109-07849d59-ee63-482f-b398-c445ec898c90.png)

**Comment by GlennGoddard** [comment]
If you search the WeatherFlow forums for false lightning, you should find some post on ways to find 'leaks' such as tuning a radio to a non-station and hearing the electrical discharge.  My issue (I think) was a solar panel for a motion light, I just moved the Tempest a little bit away from it and my false lightning count disappeared.

Are you on a septic system?
The time interval and the apparent magnitude of your spikes looks like possibly a septic pump timing or a HVAC fan maybe (at least on the 18th).  Bear in mind the issue may not even be on your property.  I know that some lights (mainly LEDs) are not in compliance with FCC (Federal Communications Commission...USA) regulations and cause interference (think lights imported from China).  The main culprits are 'grow' lights.

**Comment by Vitani** [comment]
Unfortunately not, I did a bit of investigation, but nothing matched up or could manually "induce" a spike. Thank-you for your help & work on this add-on
