### ISSUE TITLE
Can not update to 3.1.0

### ISSUE THREAD

**Issue by olonsoft** [briis/hass-weatherflow2mqtt#153]
### Home Assistant Version?

2022.6.5

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.0.8

### What happened?

Using HA image on a Raspberry PI.
HA shows that there is an update for WeatherFlow to MQTT. 
Trying to update I get the following message:

### Relevant log output

```shell
Can't install briis/weatherflow2mqtt:3.1.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=3.1.0&fromImage=briis%2Fweatherflow2mqtt&platform=linux%2Farm64: Not Found ("manifest for briis/weatherflow2mqtt:3.1.0 not found: manifest unknown: manifest unknown")
```

**Comment by briis** [comment]
My bad. We are working on the 3.1.0 release, but it is not ready yet. I have now reverted the version number, so hopefully it will not show up. Just ignore this for now.
