### ISSUE TITLE
Add binary sensor "is_raining"

### ISSUE THREAD

**Issue by yolani** [briis/hass-weatherflow2mqtt#159]
### New Feature

Is there any chance of adding the binary_sensor.is_raining also to this. It was contained in the cloud api based integration but I ditched that to become cloud independent. I tried to create my own based on the rain rate, but that does not seem to update frequently.

**Comment by briis** [comment]
I will have a look at it.

**Comment by natekspencer** [comment]
@yolani, can you share what you used to create the binary sensor or what you mean by it didn't update frequently? The rain rate only updates once a minute from the device itself.

**Comment by yolani** [comment]
Hmm, I just checked and actually it seems to work now... I just created a binary template sensor with "rain_rate > 0?"

The first one in this picture is my own, the other one is from the cloud based integration, which seems to have a small debounce when the rain Stopps, but actually mine turns on faster. 

![image](https://user-images.githubusercontent.com/219931/177822844-f3df4ab5-c30a-4706-b0f7-f102d04a02f8.png)

**Comment by briis** [comment]
Glad it works, I will close the issue.
