### ISSUE TITLE
Question/Concern about persistence of the Home Assistant Entities 

### ISSUE THREAD

**Issue by TopBanana123** [briis/hass-weatherflow2mqtt#171]
Hi,

Hopefully this is an okay to ask this question. I posted it in the Tempest forums but they are not very active so I thought I would post here too

Thanks for your work on this project. I set it up very quickly and it works great. Before I was relying on going out to the Weatherflow API over the internet, so any of my automations involving the Tempest would fail if the internet didn’t work, or they had an outage. This is so much better, especially given than reliable, powered LUX sensors seem far and few between

I did have a question, I noticed that I never had to create the Tempest weather station, it just showed up all on its own. Will it disappear all on its own if the Tempest is off?

My reason for asking is that I am using all of my Home Assistant devices in HomeKit, and all my automations are in Homekit. When I removed my old Tempest config (It came through HomeBridge) I watched all of my automations disappear in HomeKit

My concern is that one day the Tempest has an issue, or the AP it connects to has an issue, and it just disappears from Home Assistant, and then all my automations in HomeKit will just vanish

Thanks!

**Comment by briis** [comment]
I Guess you saw the answer from @natekspencer on the Tempest Community, but I [post it here](https://community.weatherflow.com/t/weatherflow2mqtt-for-home-assistant/13718/85?u=bjarne) for others to see
