### ISSUE TITLE
Forecasted Temperatures not correct

### ISSUE THREAD

**Issue by jsb2092** [briis/hass-weatherflow2mqtt#173]
### Home Assistant Version?

2022.7.7

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.1

### What happened?

When using the HA weather integration, the temperature unit for the the current temperature is in F, however, the temperatures for the forecast appear to be treated as F numbers that have been converted to C.

temperature: 72
temperature_unit: °F
humidity: 69
pressure: 0.88
pressure_unit: inHg
wind_bearing: 115
wind_speed: 1.52
wind_speed_unit: mph
visibility: 17.3
visibility_unit: mi
precipitation_unit: in
forecast: 
- datetime: '2022-07-27T04:00:00+00:00'
  conditions: Rain Possible
  condition: rainy
  temperature: 180
  templow: 135
  precipitation: 0
  precipitation_probability: 30
  precip_icon: chance-rain
  precip_type: rain
  wind_speed: 4.82
  wind_bearing: 208
  wind_direction_cardinal: SSW

**Comment by GlennGoddard** [comment]
What units do you have selected in the settings of the App?
It appears you selected imperial this integration, is this also the case for home assistant?

**Comment by jsb2092** [comment]
In my configuration.yaml I had it set to C, however, that was because the weather card was displaying incorrectly.  However, I did update HomeAssistant this morning, and switching back to F seems to have fixed it, so closing.
