### ISSUE TITLE
unable to select nl (dutch) language

### ISSUE THREAD

**Issue by JasringStw** [briis/hass-weatherflow2mqtt#180]
### Home Assistant Version?

2022.8.6

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.1

### What happened?

I do not have the option to select nl as language and in yaml mode I can of course enter whatever I want but nl does not get accepted. see the log output.
I hope this can be fixed.

### Relevant log output

```shell
value must be one of ['da', 'de', 'en', 'fr']. Got {'STATION_ID': '81280', 'STATION_TOKEN': '<value>', 'FORECAST_INTERVAL': 30, 'LANGUAGE': 'nl'}
```

**Comment by briis** [comment]
I am pushing out 3.1.2 right now, which is the first release with support for Dutch. Should be available in approximately 30 min.

**Comment by briis** [comment]
3.1.2 is now available as Add-On or Standalone Container. NL is now supported as language.

**Comment by JasringStw** [comment]
Great, that's really quick, thanks

**Comment by briis** [comment]
I forgot to update a version flag, so it will be V3.1.3 that is the right version. This is available now also
