### ISSUE TITLE
Unable to Load Home Assistant core config: unexpected mimetype text/plain

### ISSUE THREAD

**Issue by allout58** [briis/hass-weatherflow2mqtt#181]
### Home Assistant Version?

2022.8.6

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.1

### What happened?

1) No errors in logs :smile: 
2) I'm having an issue where the forecast is in Celsius but HA is interpreting it as Fahrenheit. I'm not sure this is directly related, but I'm trying to narrow down my options

### Relevant log output

```shell
ERROR:weatherflow2mqtt.weatherflow_mqtt:Could not read Home Assistant core config: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://supervisor/core/api/config')
```

**Comment by allout58** [comment]
Ah, that does seem to be the cause of my imperial/metric issue. Went in and hacked the default value to be UNITS_IMPERIAL and my issue went away. Seems like because it can't read the config from supervisor, it's just doing the defaults

**Comment by briis** [comment]
Could you post the output of the file `/config/.storage/core.config`, because this is what we read to find the unit_system, unless you specifically specify it in the config file for the Add-On.

Mine looks like this (with some redacted values):

```json
{
    "version": 1,
    "minor_version": 1,
    "key": "core.config",
    "data": {
        "latitude": REDACTED,
        "longitude": REDACTED,
        "elevation": 54,
        "unit_system": "metric",
        "location_name": "Hjem",
        "time_zone": "Europe/Copenhagen",
        "external_url": "REDACTED",
        "internal_url": "http://REDACTED:8123",
        "currency": "DKK"
    }
}
```

**Comment by allout58** [comment]
Here's the file. Using the old Portainer addon to exec into the addon, I couldn't find a `/config` folder, so I just used the SSH addon to get it.
```json
{
  "version": 1,
  "minor_version": 1,
  "key": "core.config",
  "data": {
    "latitude": 0,
    "longitude": 0,
    "elevation": 0,
    "unit_system": "imperial",
    "location_name": "Home",
    "time_zone": "America/New_York",
    "external_url": "redacted.ui.nabu.casa/",
    "internal_url": null,
    "currency": "USD"
  }
}
```

Seems to match your file

**Comment by briis** [comment]
Thanks. 
Are the latitude and longitude 0 numbers something you just typed in this file now, or did you not set them in Home Assistant? That can cause the error reading the JSON file, as these values are also read from here.

**Comment by allout58** [comment]
Ah, no, that was me redacting it. Elevation is actually set to 0 though, I just haven't bothered to figure it out and set it in HA.

**Comment by allout58** [comment]
Well, not sure what was going on, but the update did fix the issue for me. I'll close this issue, thanks for the quick responses though!

**Comment by briis** [comment]
Re-Open if you see this again.

**Comment by allout58** [comment]
I occasionally see this still, seems like kinda just random chance (so, probably actually a timing issue 😬)

**Comment by briis** [comment]
Without more data to debug on, it is hard to say what is going on. When it happens could you check in the Add-On if anything turns up in log.
