### ISSUE TITLE
Add translation for battery mode

### ISSUE THREAD

**Issue by MichelJourdain** [briis/hass-weatherflow2mqtt#185]
### New Feature

The translation of the battery modes would be nice.  In French it could be this.

         {% if states.sensor.tempest_st_00032986_battery_mode.state | int == 0 %}
              Tous les capteurs sont activés et fonctionnant à pleine puissance.
              Intervalle d'échantillonnage du vent toutes les 3 secondes
          {% elif states.sensor.tempest_st_00032986_battery_mode.state | int == 1 %}
              Intervalle d'échantillonnage du vent réglé sur 6 secondes.
          {% elif states.sensor.tempest_st_00032986_battery_mode.state | int == 2 %}
              Intervalle d'échantillonnage du vent réglé sur une minute.
          {% elif states.sensor.tempest_st_00032986_battery_mode.state | int == 3 %}
              Intervalle d'échantillonnage du vent réglé sur 5 minutes.
              Intervalle d'échantillonnage de tous les autres capteurs réglé sur 5 minutes.
              Le capteur de pluie haptique est désactivé de l'écoute active.
          {% else %}
              Indéterminé
          {% endif %}

**Comment by briis** [comment]
I will look in to this.

**Comment by GlennGoddard** [comment]
This will require a separate function for the battery mode text and then use the following but the above french relevant lines in the translation.  The text function would only take the battery mode number and then pull of the translation; exactly like how the Zembretti Text is done.

I have a concern that the text might be too long when combined with everything else in the MQTT topic.  I don't know if it is or not, but it is something to keep in mind.

This is not a direct plug and play.  I kept it in exactly the same format as above for easy comparison.

That being said, with all the other feature requests I just dropped and my mess of a PR for current conditions; it might be awhile before @briis can get to this.  This is relatively easy and straight forward, and can do a PR for it myself, but personal preference is to get local current conditions up and running first.

English:
```
if states.sensor.tempest_st_00032986_battery_mode.state == 0:
      print("All sensors are activated and running at full power. Wind sampling interval is set to 3 seconds.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 1:
      print("Wind sampling interval is set to 6 seconds.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 2:
      print("Wind sampling interval is set to one minute.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 3:
      print("Wind sampling interval is set to 5 minutes and all other sensor sampling interval is set to 5 minutes, haptic rain sensor is deactivated from active listening.")
else:
      print("undetermined")

```
Danish:
```
if states.sensor.tempest_st_00032986_battery_mode.state == 0:
      print("Alle sensorer er aktiveret og kører med fuld kraft. Interval for vindprøvetagning er sat til 3 sekunder.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 1:
      print("Interval for vindprøvetagning er sat til 6 sekunder.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 2:
      print("Interval for vindprøvetagning er sat til et minut.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 3:
      print("Interval for vindprøvetagning er sat til 5 minutter og interval for alle andre sensorer er sat til 5 minutter, haptisk regnsensor er deaktiveret fra aktiv lytning.")
else:
      print("ukendt")

```
Dutch:
```
if states.sensor.tempest_st_00032986_battery_mode.state == 0:
      print("Alle sensoren zijn geactiveerd en draaien op volle kracht. Interval voor windmeting is op 3 seconden gezet.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 1:
      print("Interval voor windmeting is op 6 seconden gezet.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 2:
      print("Interval voor windmeting is op een minuut gezet.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 3:
      print("Interval voor windmeting is op 5 minuten gezet en het interval voor alle andere sensoren is op 5 minuten gezet, haptische regensensor is uitgeschakeld van actief luisteren.")
else:
      print("onbekend")

```
German:
```
if states.sensor.tempest_st_00032986_battery_mode.state == 0:
      print("Alle Sensoren sind aktiviert und arbeiten mit voller Leistung. Intervall für die Windmessung ist auf 3 Sekunden eingestellt.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 1:
      print("Intervall für die Windmessung ist auf 6 Sekunden eingestellt.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 2:
      print("Intervall für die Windmessung ist auf eine Minute eingestellt.")
elif states.sensor.tempest_st_00032986_battery_mode.state == 3:
      print("Intervall für die Windmessung ist auf 5 Minuten eingestellt und das Intervall für alle anderen Sensoren ist auf 5 Minuten eingestellt, haptischer Regensensor ist von aktivem Zuhören deaktiviert.")
else:
      print("unbekannt")
```

**Comment by GlennGoddard** [comment]
After further thought, this is a lot of text to add to the MQTT string, maybe too much.

**Comment by MichelJourdain** [comment]
Ok, no problem.

**Comment by GlennGoddard** [comment]
While I got you here, please review this:

        "lightning-rainy": "Eclair & Pluie",
        "lightning": "Eclair",
        "hail": "Grele",
        "pouring": "Pluie battante",
        "snowy-rainy": "Neige & Pluie",
        "rainy": "Pluie",
        "windy-variant": "Vent & Pluie",
        "windy": "Vente",
        "fog": "Brouillard",
        "snowy": "Neige",
        "cloudy": "Nuageux",
        "partycloudy": "Partiellement Nuageux",
        "sunny": "Ensoleille",
        "clear-night": "Nuit Claire"

**Comment by MichelJourdain** [comment]
Voilà. 😀

   "lightning-rainy": "Éclair & Pluvieux",
    "lightning": "Éclair ",
    "hail": "Grêle",
    "pouring": "Pluie battante",
    "snowy-rainy": "Neigeux & Pluvieux",
    "rainy": "Pluvieux",
    "windy-variant": "Venteux & Pluvieux",
    "windy": "Venteux",
    "fog": "Brouillard",
    "snowy": "Neigeux",
    "cloudy": "Nuageux",
    "partycloudy": "Partiellement Nuageux",
    "sunny": "Ensoleillé",
    "clear-night": "Nuit Claire"

**Comment by GlennGoddard** [comment]
@MichelJourdain 
2nd review:

        "lightning-rainy": "Éclair & Pluvieux",
        "lightning": "Éclair",
        "hail": "Grêle",
        "pouring": "Pluie Battante",
        "snowy-rainy": "Neigeux & Pluvieux",
        "rainy": "Pluvieux",
        "windy-variant": "Venteux & Pluvieux",
        "windy": "Venteux",
        "fog": "Brouillard",
        "snowy": "Neigeux",
        "cloudy": "Nuageux",
        "partycloudy": "Partiellement Nuageux",
        "sunny": "Ensoleillé",
        "clear-night": "Nuit Claire"

**Comment by MichelJourdain** [comment]
??? Did you change anything?

**Comment by GlennGoddard** [comment]
"pouring": "Pluie Battante",

capitalized B...I will take your response as it being good then

**Comment by MichelJourdain** [comment]
Ok, 

"pouring": "Pluie battante",
