### ISSUE TITLE
Add sensor to indicate if hub is connected to servers

### ISSUE THREAD

**Issue by rodrigus32** [briis/hass-weatherflow2mqtt#187]
Would be great to have a sensor that indicates is the hub is connected to the servers. This way we can automate things smart plugs to reset the hub.

**Comment by briis** [comment]
To make sure I understand this: You want a sensor that indicates if the Hub is transmitting data to the Tempest Servers. Is that correct?
If this is correct, that is not currently possible. There is nowhere in the UDP API, that this data can be retrieved. 

The only way I currently think this could be done is polling the servers, to check when data was last updated. But that somehow defeats the purpose of having a local solution. I know we already pull servers when getting the Weather Forecast, but that brings a different dataset.

**Comment by rodrigus32** [comment]
Could it be done by the color of the light on the hub? A green light indicates is online, thus by polling locally the color of the light get the online/offline status. If not I understand.

**Comment by briis** [comment]
This is not exposed in the API. I will need to do some test on some other areas just to see if this somehow indicates this.

**Comment by rodrigus32** [comment]
Thanks!

**Comment by GlennGoddard** [comment]
If you go to the WeatherFlow forum you could recommend they add that to the API and then it would be easy to implement.
