### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by timothybuchanan** [briis/hass-weatherflow2mqtt#188]
This add-on was working, but suddenly stooped today with this error in log:
INFO:weatherflow2mqtt.weatherflow_mqtt:🏠 Home Assistant Supervisor Mode 🏠
INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is America/Denver
ERROR:weatherflow2mqtt.weatherflow_mqtt:Could not connect to MQTT Server. Error is: [Errno 111] Connection refused
I tried reinstalling both this add-on and MQTT. MQTT discovers the devices and entities on start, but the sensors show unavailable.

**Comment by briis** [comment]
The error message is pretty clear, the integration cannot connect to your MQTT server. You will have to check that you can connect to MQTT with the credentials you supplied in another way, to verify what is wrong.

**Comment by timothybuchanan** [comment]
That was the first thing I checked, and the MQTT server did respond to test messages published. I tried reinstalling and restarting HA several times, but the error was finally fixed with terminal command “sudo reboot.”

**Comment by briis** [comment]
Glad is it fixed. I am positive this is not related to this Integration, as all it just publishes message to MQTT like any other app.
So there must have been a glitch somewhere, that the reboot fixed.
