### ISSUE TITLE
Can you autocreate the config.yml in case it does not exist?

### ISSUE THREAD

**Issue by msperl** [briis/hass-weatherflow2mqtt#19]
This would make the setup easier for lots of use cases.

probably a minimal wrapper script would be needed that would check for the config and copy it in case it does not exist. Then execute the python script.

Or you add sensible defaults in case the file does not exist in python itself - the relevant method returns None right now, so change that to return the default structure.

**Comment by briis** [comment]
Hi,
If the method returns None, all sensors are loaded by default. So only in the case where there are sensors you do NOT want, the file is needed.

Did you experience any issues with this method?

**Comment by msperl** [comment]
Reading the documentation it reads unfortunately a bit differently:

Quote from the README.md: `It is also in this directory that you must place the config.yaml file if you use this`

So I assumed that it is a necessity to place that file.

**Comment by briis** [comment]
Quote from the Installation section:
>If you don't want all sensors setup, copy the config_example.yaml file from this repo to that directory, and rename it to config.yaml

So only if you don't want to have all sensors, then you must use this.

**Comment by msperl** [comment]
well - I read the Readme.md as: you always have to provide the config and it will fail otherwise...

**Comment by briis** [comment]
OK, that is good to know. I will see if I can re-formulate it, so it is more clear that it is not needed.
