### ISSUE TITLE
Lightening Functions, Counter, Distance, Last Hour, etc. Not Recording in Home Assistant.

### ISSUE THREAD

**Issue by craigccfl** [briis/hass-weatherflow2mqtt#190]
### Home Assistant Version?

20223.9.1

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

weatherflow2mqtt:latest

### What happened?

Everything works on the tempest app. Everything but the lightening functions working on HA. 
![image](https://user-images.githubusercontent.com/38798834/189497122-cb9e4429-5a9f-44a9-8491-b1bcd757046e.png)

### Relevant log output

```shell
mqtt explorer
sensor:
{"name": "Tempest ST-00084636 Lightning Count (Last hour)", "unique_id": "ST-00084636-lightning_strike_count_1hr", "icon": "mdi:weather-lightning", "state_topic": "homeassistant/sensor/weatherflow2mqtt_ST-00084636/observation/state", "value_template": "{{ value_json.lightning_strike_count_1hr }}", "json_attributes_topic": "homeassistant/sensor/weatherflow2mqtt_ST-00084636/lightning_strike_count_1hr/attributes", "device": {"identifiers": ["weatherflow2mqtt_ST-00084636"], "manufacturer": "WeatherFlow", "name": "Tempest ST-00084636", "model": "Tempest", "sw_version": "172", "via_device": "weatherflow2mqtt_HB-00068873"}}

Events are triggerd from the weather hub to mqtt but the message is not recorded in HA

Tried this with mqtt on HA and in different docker containers, same with weatherflow2mqtt.
```

**Comment by MichelJourdain** [comment]
I have the same problem, there was a storm today, the application calculated 77 and weatherflow2mqtt calculated only 1.

![1C97D27D-D588-4739-B2D7-4F169803C924](https://user-images.githubusercontent.com/83040228/189990603-0ebb745b-39a0-4514-a652-6f49e4d9e3c3.jpeg)

![749959CC-2A22-443C-90F4-3C63F0A548B2](https://user-images.githubusercontent.com/83040228/189990608-c867d85c-7e0d-451b-a2bf-1fdc3a48c13a.jpeg)

**Comment by sirmeili** [comment]
I've also noticed that lightning is not recorded properly. Even last lightning strike seems to be off.
