### ISSUE TITLE
Calculated Sensors with "None" in Battery Mode 3

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#194]
### Home Assistant Version?

2022.11.5

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

3.1.3 (latest Dev)

### What happened?

In Battery Mode 3 the calculated sensors of Beaufort Scale, Zambretti Number and Zambretti Text do not get any output.

I need to gather more data but in Mode 3 there is no:
Beaufort Scale (need to pull from wind speed non averaged; Tempest documentation was not correct last time this happened) (None Reported)
Wind Bearing Avg (None Reported)
Wind Direction Avg (None Reported)
Wind Gust (None Reported)
Wind Lull (None Reported)
Wind Speed Avg (None Reported)
Zambretti Number (uses average wind direction, need to change to non average) (None Reported)
Zambretti Text (no Zambretti Number output) (None Reported)
No Lightning or rain detection (expected) 

Still get:
Wind Direction
Wind Bearing
Wind Speed

Only been in mode 3 for an hour; so I'm not sure what other calculations are affected yet.

I will look thru to code for the following just to be sure; just documenting for future reference.
I suspect Cloud Base is not getting updated, still has a number thou. I will keep an eye on this.
Fog Probability (currently at 87% but no change since mode 3)
Snow Probability (currently at 0% seems to have stopped at mode 2)
Visibility

Freezing Level seems to be tracking well
Need to look at UV and Lux levels when the sun is above the horizon.
Absolute Humidity and Air density seem to be tracking well.

NOTE: need to contact WeatherFlow since app will not report any wind information, even thou it is provide from the Tempest at reduced intervals.

**Comment by briis** [comment]
It's been a while since I had the code open, but all the None values are because the calculated value is missing one or more sensor values to be able to calculate it properly. Not sure if we should do anything about it, as this is simply how the Tempest device operates. (Mine had no issues last winther and never went in to mode 2 or 3)
I have a Davis Vantage Vue very close to my tempest, and this has never lost battery due to the dark hours in the Winther.

**Comment by GlennGoddard** [comment]
I will see if it makes any sense to use the the non-average for wind.  I will say that that getting a 'None' is better than it crashing.  I would like to say that this should be a rare condition but this is the 2nd time this year I have gone into Mode 3.  I agree that is how it operates, but I also like as much as I can get; that being said I may have to invest in the power booster.

I do think the normal output is better using the wind averages but I might see if I can send both Avg and non-average values and fall back to non-average if average is a 'None'.  It may not be worth the effort but I can still try.

On another note, I have the local conditions working fairly well, exception being night time.  Life keeps throwing stuff at me to not get a chance to put it into GitHub.

**Comment by GlennGoddard** [comment]
I think the best option is for me to get the power booster accessory and then not have to worry about this.
If others have this issue and do not desire to get the power booster, I might look into making this work better; but I think I am currently in the vast minority that actually has this problem.   I'll close this once I get my power booster, if there is a delay then I might work on this.

**Comment by GlennGoddard** [comment]
FYI

For my Tempest when voltage drops to 2.15V then the readings are every two hours.
The good news is that this integration does not crash and will continue to relay the information as/when it receives it.

**Comment by GlennGoddard** [comment]
I decided to not change the input variables since my Power Booster is supposed to come today.
I might however change the low end of the battery voltage for percentage calculation.  Anything below 2.11V results in complete shutdown of the Tempest.

**Comment by GlennGoddard** [comment]
@briis

1.8V is 0% per battery manufacturer; however, Tempest will not function at <2.11V (based on multiple personal observations).  So...I initially capped 0% at 1.8 based on the actual battery, would it make more sense to change it to 2.10 for 0% to hopefully give a more realistic useful battery percentage as used by the Tempest?

I don't have any additional data for Sky and Air; so I will leave them at what the actual battery specs are for now.

**Comment by briis** [comment]
Yes I do believe that would make sense. I will do that, and then release an official new version.

**Comment by briis** [comment]
3.1.4 is now released, with this change incorporated.
