### ISSUE TITLE
No Lightning strikes 

### ISSUE THREAD

**Issue by wontonfrays** [briis/hass-weatherflow2mqtt#195]
I added WeatherFlow to MQTT (version: 3.1.3) to my Home Assistant (Supervised / 2022.12.6) and all the Tempest data comes across with the exception of the lightning strikes. I do see lightning strikes logged in the Tempest app and website does.

**Comment by briis** [comment]
The lightning you see in the Tempest APP did they occur while you had this Add-On running?

**Comment by wackyhobo** [comment]
Yes, the lightning I saw was on the Tempest APP did occur while I had the Add-On installed and running. Both the Tempest IOS APP and the Tempest website (https://tempestwx.com/) record lightning occur but I never see it in the WeatherFlow to MQTT addon in Home Assistant.

I removed the WeatherFlow to MQTT addon in Home Assistant, rebooted my Home Assistant host (Intel NUC) and re-added the WeatherFlow to MQTT addon in Home Assistant but this did not help.

Any Ideas?

**Comment by FutureGUIs** [comment]
I am having the same issue

**Comment by depasseg** [comment]
I'm experiencing the same thing.  The app shows lightning strikes, in fact Tempest app sends me a lighting strike alert, but nothing gets logged in HA.

**Comment by dan-s-github** [comment]
I can't see a reference to this issue in latest changelog and wonder if this was related to another issue.
Unfortunately the last lightning detection in the app was 2 weeks ago, so need to wait for next one to see if it shows up.
Anyway thanks for the add-on but a comment when closing issue would still be appreciated.
