### ISSUE TITLE
Snow Probility exceeds 100%

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#196]
### Home Assistant Version?

2022.12.1

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

Currentl Latest Dev Build

### What happened?

I will handle the PR for this, but just putting it in as an issue.  Just noticed I have a 209% chance of snow.  I will set an upper limit, probably 99%.  Although it is currently an accurate probability, it should be limited on the apocalypse predictions.  This might be related to my station in LOW LOW LOW power mode, but I think I accounted for that; but still going to do a limit.

**Comment by briis** [comment]
No worries. I am doing some work right now, so I have implemented a fix for that, ensuring that snow probability does not exceed 100
