### ISSUE TITLE
Add WeatherFlow2MQTT Version Sensor

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#197]
### New Feature

For ease of bug reporting and troubleshooting it would be convenient to have a sensor for the currently running version of this integration.

It could be an independent sensor or an attribute to an existing sensor such as Station Status, Hub Status, or Weather.  I can see arguments either way.  I think independent would be the most convenient.

**Comment by briis** [comment]
I have decided not to create another sensor, so this is now added as an Attribute to the Hub Status Sensor. You can easily retrieve the value by using something like this `{{ state_attr("sensor.hub_hb_xxxxxxxx_status", "version") }}`.
I will release a new dev version later today.

**Comment by GlennGoddard** [comment]
@briis You updated the docker image but didn't update here on github.  I was going to update the ReadMe to reflect the version number; but noticed my fork was up-to-date which it should not have been.

**Comment by briis** [comment]
Ups.... Yes sorry, I did it again. Updated now.

**Comment by GlennGoddard** [comment]
@briis submitted simple PR for ReadMe stating Version for Integration under Status
