### ISSUE TITLE
Sensor Naming Convention

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#20]
It would be convenient for setting up cards and for a 'maybe' better searching experience.
Having generic names for Humidity, Temperature, etc makes it difficult (sometimes) to find a sensor from this integration.
I realize that this would require fixing all instances in ones HA to the corrected sensor name.
That said, I think a prefix for the sensor names such as "wf" would be helpful.  For example sensor.humidity would now be sensor.wf_humidity

**Comment by briis** [comment]
Agree. I think the user base is still so small that it will not be a major issue. It will be a BREAKING CHANGE though

**Comment by briis** [comment]
I have now released V2.0, where this is included. See the CHANGELOG.md for more info.
