### ISSUE TITLE
Possible storage values

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#21]
Since a database is being implemented, have you considered logging Highs/Lows.
High/Low for
Temperature
Humidity
DewPoint
Illuminance
Rain Duration (just highest)
Rain Rate (just highest)
Wind Gust (high)
Wind Lull (high)
Wind Speed (high)
Lightning Energy
Lighting Count
Sea Level Pressure
UV Index
Solar Radiation
(ok, pretty much everything)

The high lows could be for the week (last 7 days) / month (last 30 days) / year (last 366 days, account for leap years) and maybe of all time.

And maybe some sort or reset.  I am specifically thinking of lightning info since my lightning sensor has gone crazy is thousands of reported strikes a day.

Maybe more trends also, such as rain increasing/subsiding or wind.  Sea Level Pressure trend is already in work.

**Comment by briis** [comment]
Hi Glenn,
The above was one of the reasons to switch to a database, as these type of sensors need more data to be recorded. So it is on the list, but it will take a little time before I get it done. I will be busy with my real job the next weeks 😁

**Comment by GlennGoddard** [comment]
Based on a new post from the WeatherFlow forums....
Accumulated rain fall over a period.

**Comment by briis** [comment]
I will close this now, as the work has started and some of it has been delivered. More to come over time.
