### ISSUE TITLE
API Key is invalid or does not support this operation

### ISSUE THREAD

**Issue by wptracy** [briis/hass-weatherflow2mqtt#210]
### Home Assistant Version?

Home Assistant 2023.1.4

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

Current version: 3.1.6

### What happened?

I have confirmed that I have configured the correct token and URL
I created a token in https://tempestwx.com/settings/tokens and pasted it in the configuration and saved it.
https://tempestwx.com/station/61694/
![Screenshot from 2023-01-16 11-37-43](https://user-images.githubusercontent.com/78648145/212746721-f9b7e0d9-7600-4697-9f9c-bfd5067d8756.png)
```
Log Reports:
NFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Tempest sensor: Snow Probability
INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Status
INFO:weatherflow2mqtt.weatherflow_mqtt:Setting up Hub sensor: Weather
ERROR:weatherflow2mqtt.forecast:Your API Key is invalid or does not support this operation
WARNING:weatherflow2mqtt.forecast:Forecast Server was unresponsive. Skipping forecast update
ERROR:weatherflow2mqtt.forecast:Your API Key is invalid or does not support this operation
WARNING:weatherflow2mqtt.forecast:Forecast Server was unresponsive. Skipping forecast update
```

**Comment by briis** [comment]
You have entered the Station ID wrong. Just type the number like: 61694.
Please try again with this entry

**Comment by wptracy** [comment]
Thanks, that fixed it.  Now it works

**Comment by briis** [comment]
Perfect.
