### ISSUE TITLE
Simplify, just publish (or document) to MQTT sensor values withOUT HA fluff?

### ISSUE THREAD

**Issue by deepcoder** [briis/hass-weatherflow2mqtt#211]
Thank you very much for the fine code!

Is there some documentation of the MQTT message structure? I'm a simple guy, I would like to first see what is being published in terms of real/derived sensor readings before I dive into adding everything to Home Assistant, and being at the beckon of where the sensors end up and how they are named. I would like to see the hierarchy spelled out for which paths are readings and which are setup.

Can I set something in the .yaml file so your app does not publish all the Home Assistant sensor setup stuff and just publish what is being sent from the Tempest device?

All the HA auto setup stuff obscures the data. Sometimes less is better, especially to start, IMHO. Thx!

FYI: You have a spelling error in the bug request form "Feature Reuest"

**Comment by briis** [comment]
This uses the standard Home Assistant MQTT Discovery settings so the MQTT topic will be `homeassistant/sensor/weatherflow2mqtt/` and then everything below that.

If you take a look at the README file you will find a section with the below, which enables you to filter the sensors you take in to the system:

> If you don't want all sensors setup, copy the config_example_TEMPEST.yaml or config_example_AIR_SKY.yaml file from this repo to that directory, and rename it to config.yaml. Then add or remove the sensors you want from the [available sensors list](https://github.com/briis/hass-weatherflow2mqtt#sensor-structure). If you don't do this, all sensors from the [Available Sensors](https://github.com/briis/hass-weatherflow2mqtt#available-sensors) will be added.

And thanks for the hint on the spelling error - now corrected.

**Comment by deepcoder** [comment]
Thank you for the reply and again your work!

As I an a noob with the Tempest, I am learning everyday. I found some python code that emits the raw data from the device in a simpler format to the console and MQTT. I think I will use this for now as I learn what the Tempest can do and how I want to integrate into the home and Home Assistant.

If I circle back to using your code and if time permits, I will try to contribute.

It seems that your code publishes three main topics for each Tempest:

homeassistant/sensor/weatherflow2mqtt
homeassistant/sensor/weatherflow2mqtt_HB-xxxxxxxx
homeassistant/sensor/weatherflow2mqtt_ST-xxxxxxxx

It appears that you publish the realtime data in the third topic branch under:
observations/state
rapid_wind/state
status/attributes

But what if anything changes in the other topics, or are they just for the sensor creation in HA. However, some do seem to have dynamic data in them.

However, I have not watched it for a sufficient period I think. And, to my core point, all the fluff stuff that you are publishing to MQTT makes it difficult to wrap my head around the dynamic data. Just an option to turn off the HA dynamic sensor creation stuff for a time would really help IMHO.

So far, I am not clear on all the other topics. It appears some of them update, but I do not see them change over time for the most part. Example, there appear to be three 'battery' related topics. However, in none of them do I see the battery voltage, level or mode. Only in the observation/state topic. Should the dynamic values be under 'state' or 'attributes' topic? Some under one, some under the other.

Maybe my mqtt server is overloaded, that I am not seeing updates? Or that I am running docker in a vm under proxmox?

I'm not sure how to read your 'available sensors' documentation, I think these document the sensors that will appear in Home Assistant if I allow HA to automatically add them. FYI, there seem to be two lines called 'status', they seem the same. There are only two battery fields in the documentation, however it appears that the MQTT topics describe three topics, voltage appears missing in documentation.

I think there is nothing really here, so I close. Again, thanks for your work!!

**Comment by deepcoder** [comment]
closed.
