### ISSUE TITLE
Difference in 'Feels Like' values

### ISSUE THREAD

**Issue by pgneir** [briis/hass-weatherflow2mqtt#214]
### Home Assistant Version?

2022.12.8

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.6

### What happened?

Greetings,
I have installed this add-on along with mqtt and HA in a docker based system. I don't know the exact version that is running, but I pulled the package (as latest) about a week ago, so I assume the version is similar. My problem is that there is a disparity between the Tempest data and the HA data regarding 'Feels Like' temperature. The HA data is always several degrees cooler than what I see from Tempest.  Is this to be expected or have I missed something in configuration?

**Comment by briis** [comment]
Feels like temperature is a calculated value, and the formular Tempest uses is not the same as this Integration uses for calculating this, so having a difference is not a bug. One can then always argue what is the 'right' value, thus the right formular.

**Comment by pgneir** [comment]
Thank you for the reply. It answers my question. I was actually just
concerned about why the values were different since it is given the same
identification. It might be a good idea to note that somewhere in your
github webpage. Do you have a document showing your formula?

You are correct. There is a lot of confusion about determining this kind of
data. It can be too subjective. I have been looking at 'Wet-bulb Globe
Temperature'. It might be a better representation. Maybe..  (shrug)
