### ISSUE TITLE
Solar Elevation has a time shift

### ISSUE THREAD

**Issue by benquan** [briis/hass-weatherflow2mqtt#215]
### Home Assistant Version?

2023.2.4

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.6

### What happened?

Solar elevation seems to have a time shift, and it could be related to the time Zone.

This is a midnight to midnight graph. Near midnight you should see the lowest elevation and at noon the highest. But its shifted by 6hrs and my time zone is -6UMT.
<img width="1167" alt="Screenshot 2023-02-14 at 4 54 12 AM" src="https://user-images.githubusercontent.com/3030645/218715541-eeca6e79-213d-40f9-bcb6-50f23a75dbd3.png">

This happened before and it fixed itself but now its back with the error.

**Comment by GlennGoddard** [comment]
Do you have LAT & LONG setup in HA? (add-on pulls from HA data, Docker version is an environmental variable)
It diffidently does look off.  Verify your LAT/Long and the time zone.

Setup a graph that has solar elevation, solar insolation, and solar radiation and post the results of that.  From what you have above I would expect solar insolation to follow your solar elevation (both being wrong).  If you have don't have too many clouds or shading then the solar radiation will help with solar noon.  For clarification: Solar noon is the highest point, this is not the same as clock noon 1200.  Solar midnight is the low point, and not the same as midnight.  They will be close but unlikely to be the same time.

Also, verify your system time is correct for your time zone.

I will probably send you the Solar Elevation equation and have you run that and compare the results to what HA is providing.

**Comment by benquan** [comment]
I do have LAT LONG in HA. For the moment the problem corrected itself. I never changed neither time zone nor LAT LONG details. But it already was the second time it happened. The other time it also corrected itself.

**Comment by briis** [comment]
Most likely related to #198 
New releases try to ensure correct units and timezone is set no matter what.
