### ISSUE TITLE
Slovenian language not available

### ISSUE THREAD

**Issue by prigorus** [briis/hass-weatherflow2mqtt#236]
### Home Assistant Version?

2023.6.3

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.2.0

### What happened?

Slovenian (si) language is supposed to be added but is not available from the list of available languages.

**Comment by briis** [comment]
The file was there, but placed in a wrong directory, so it was not available to the integration. Everything is now in its place and Slovenia is added to the list of languages. It will be in release 2.3.2, which is waiting for a few more changes before release.
