### ISSUE TITLE
Rainfall today does not much web interface

### ISSUE THREAD

**Issue by madasus** [briis/hass-weatherflow2mqtt#237]
### Home Assistant Version?

2023.8.4

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

3.2

### What happened?

The rainfall totals do not seem to match the web interface.  I wonder if these is a problem with the conversion from metric to imperial? I have everything set to imperial

From web interface

![image](https://github.com/briis/hass-weatherflow2mqtt/assets/9310056/f19154bd-62db-4f09-827d-6b4a9fb04ef1)

From MQTT

![image](https://github.com/briis/hass-weatherflow2mqtt/assets/9310056/c1db79e0-0a80-4655-91b5-7b072e9fd74d)

What HA shows

![image](https://github.com/briis/hass-weatherflow2mqtt/assets/9310056/1e786d58-1f71-4e50-926c-9ee7198194cc)

Thank you

**Comment by mccabery** [comment]
I believe the discrepancy is due to the "raincheck" implementation. [https://community.weatherflow.com/t/introducing-raincheck/3699](url)

**Comment by madasus** [comment]
@mccabery I don't believe that is the case.  This is not related to the average but the accumulated for the current day.

It sounds like raincheck is focused on the previous day.

"We’re launching “RainCheck” starting with all owners in the Continental USA. Every day, between midnight and 8am (depending on weather conditions),"

**Comment by madasus** [comment]
@mccabery Thanks - I turned it off just to see if that corrects for the next storm.

The question is wouldn't this interface still pull the updated numbers so that what is pulled would match the web interface?

**Comment by briis** [comment]
The thing is, that the UDP API, only reports the Rain amount over previous minute. So this integration has to summarize this and then reset again when hitting midnight. If you restart, for some reason during the day, the counter may get reset too, and the numbers in the WeatherFlow database might not fit with the numbers here.

All data coming from the UDP API are in Metric format, so a conversion has to take place, but this should not create that discrepancy.

**Comment by briis** [comment]
> Sounds like this is just something we have to live with if we want a truly local interface?

Yes unfortunately. I live in Europe, so we don't have the NearCast option, so it is also hard to test. Anyway, as you said, if you want a truly local system, this is how it is.

I will close this now.
