### ISSUE TITLE
Documentation Needed for breaking change - "No statistics found" for some sensors but long term data is available

### ISSUE THREAD

**Issue by frederickjh** [briis/hass-weatherflow2mqtt#243]
### Home Assistant Version?

2023.9.2

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.2.1

### What happened?

I noticed this because I have a Statistics graph Card setup to show solar radiation from the tempest for the past 7 days. It now no longer shows a graph but "No statistics found". 

I then went directly to the Tempest solar radiation sensor and got the same message of "No statistics found". However If I then click on "Show more" I see the historical data.

This is affecting the following sensors of the Tempest:

- Absolute Humidity
- Air Density
- Solar Insolation
- Solar Radiation

The other Tempest sensors seem to function correctly. I believe that this happened after one of the recent update. I have looked at how to go back to an older version but have not found information on how to do this so I can test that this is a regression.

### Solar Radiation - "No statistics found" 
![Home_Assistant-WeatherFlow_Addon_Solar_Radiation_No_statistics_found-Screenshot from 2023-09-17 13-07-56](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/1e642a77-7646-4cb8-8a9e-df7bb5ace219)

### Solar Radiation - "Show more"
![WeatherFlow_Addon-Solar_Radiation_Show_more-Screenshot from 2023-09-17 13-09-22](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/cce2cefd-bfa8-4443-a1e8-b4707098c77f)

**Comment by frederickjh** [comment]
I found that these four sensors in Developer Tools > statistics had issues. Using the "Fix issue" button and update the historical units of the statistical values seems have fixed the issue. After a while I started to get blank graphs. Now I am starting to get enough data that the graph is showing some data.

![Home_Assistant_WeatherFlow_Addon_Developer_toos_statistics_fix_issueScreenshot from 2023-09-17 13-23-16](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/b67787f9-9dd6-4c9a-8d15-bd63f338bc38)


![Home_Assistant_Weatherflow_the_unit_of_this_entity_changedScreenshot from 2023-09-17 13-25-02](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/9c87207c-f86b-4317-9f81-c8792a88217b)

![Home_Assistant_WeatherFlow_Addon-Statistics_startingScreenshot from 2023-09-17 13-37-15](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/b0941c72-7c38-4b72-97c5-0bb0f067c120)



My last seven days graph is still not showing but I believe in time it will as it is set to an hour time period, so after an hour it should start to show..

This information should be added to the breaking changes for the commit regarding changing units with ^in them to match HA standards. And possibly to the documentation too.

**Comment by frederickjh** [comment]
Also, the sensors with units with ^in them need to be updated in the README.md to the new values.

**Comment by frederickjh** [comment]
I also found this in the log after the fix issues  above . . . 

![WeatherFlow_Addon_Log_messages_cannot_convert_units-Screenshot from 2023-09-17 13-52-32](https://github.com/briis/hass-weatherflow2mqtt/assets/864159/c6cc1647-ed18-4cd0-86ea-d5ecd1849f04)

Looks like three of the four units could not be converted.

**Comment by briis** [comment]
The documentation is now updated, showing the correct units used.
