### ISSUE TITLE
Visibility Calculation

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#26]
This can be done with the visibility_template in the weather template or you could calculate with the given station height.
This formula is for good weather, so it would be an absolute maximum visibility distance.
Later with better fog prediction, this can be dynamic instead of a set number; just trying to lay the ground work.

1.22459 * sqrt (height in feet above sea level) = Distance to the horizon in nautical miles
using 1.2 will yield good accuracy also

3.56972 * sqrt (height in meters above sea level) = Distance to the horizon in km
using 3.6 will yield good accuracy also

I can go ahead and add this in the readme with the caveat that it is the max possible and at does not change with actual conditions if you don't want to calculate it in the integration.

For example my visibility for 335 ft above see level would be:
visibility_template: "22.4"

The weather card I use "Animated Weather Card" has a place for visibility and I didn't like a blank there, so I put in a placeholder value of my visibility to the horizon.

**Comment by briis** [comment]
I will add this as a sensor. Thanks

**Comment by briis** [comment]
Released in V2.0.3

**Comment by GlennGoddard** [comment]
I am working on an improved calculation that does change visibility range based on weather conditions:
Given the max visibility already calculated, the below will give a percentage of that for visibility based on dewpoint.

Depending on how it is initially calculated:
Tair = air temperature
Tdp = Dew Point
In F:
[0.63(Tair - Tdp) - 1.15]/10
In C:
[1.13(Tair - Tdp) - 1.15]/10

With this result multiply it to the max visibility to determine visibility based on conditions (dew point).

I will look thru the code to see if I can find it and make the modifications.
