### ISSUE TITLE
Pressure sensor fault and no lightning data

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#28]
Had a small storm pass overnight and this morning found two things.  First is that weatherflow2MQTT restarted a couple of times, both apparently due to a pressure sensor fault.  This was followed by an error that "Pressure value was reported as NoneType" (see log screenshot below for details)

![Screen Shot 2021-06-22 at 8 55 57 AM](https://user-images.githubusercontent.com/42701104/122938891-c021c500-d338-11eb-8590-645db078d6ba.png)

Second is that weatherflow2MQTT did not record any lighting data, while both smartweather (REST api) and the app recorded several events.  Could be that I have an issue on the Tempest device.  I do get many "Lightning Disturber" events through the UDP interface.  I know that WeatherFlow does do some processing and perhaps what I am seeing is info collected from other devices, but I thought the the REST api included the raw lightning data.  Anyway, would appreciate information regarding the Lightning Disturber events, and perhaps confirmation that others are not having issues. 

Thanks
![Screen Shot 2021-06-22 at 8 55 57 AM](https://user-images.githubusercontent.com/42701104/122939107-f2cbbd80-d338-11eb-8371-46f38b3198c5.png)

**Comment by simonranson** [comment]
What firmware do you have on the Tempest head? I did read on the Weatherflow forums that early firmware wasn't reporting lightning over UDP - It was the case for me when I was on v134.

I put in a request to get my firmware updated due to spikes in luminescence/solar radiation, and I'm on v156 now... and waiting for a storm to see if I get lightning events on UDP.

Cheers
Simon

**Comment by briis** [comment]
I am on V156 also, and just had lightning yesterday, which recorded as expected. The way I count it is that I add one to a variable every time the `Lightning Strike Event [type = evt_strike]` occurs, and that should be the most accurate way of doing this. 

For the pressure error, I will put in some checks to ensure that we have the needed values before the calculations are done. This is just a timing issue, so you might see None or Unknown until we have all the data collected.

**Comment by briis** [comment]
Just released 2.0.5, which should fix the Pressure Trend crashing the system.

**Comment by chasut** [comment]
That station is on v150.  I saw that in the forum, but assumed I was far enough past that version that it should be ok; who knows, didn't run across release notes.

Anyway, thanks for the fix and confirmation.  I will contact support.

**Comment by chasut** [comment]
Just had a chat with support.  They say that the strikes are being recorded on the local station.  I asked again to confirm that it wasn't their crowd-sourced AI stuff.  So the mystery deepens a bit.  Unfortunately I didn't have any debugging turned on and was not logging any of the traffic.  Worst is that the further we get into summer here, the less likely I get any lightning to test with.  Any thoughts?

**Comment by chasut** [comment]
BTW, I am requesting a push of v156 so we can rule that out.

**Comment by briis** [comment]
I will go through the code tomorrow, to see if there can be a situation where I will not pick-up the strikes, but as said, it works for me.

**Comment by chasut** [comment]
I do have a lot of "Lightning Disturber" faults reported, could that be related?  They only happen when there is actual lightning activity, I have not seen any at other times that might indicate some EMI. 


![Screen Shot 2021-06-22 at 9 04 51 AM](https://user-images.githubusercontent.com/42701104/123008987-832df080-d381-11eb-89be-72d8053d3c3a.png)

**Comment by briis** [comment]
Now that you mention it: When I had Lightning occur here, two days ago, I noticed that I did not get any strike events for a little while, but instead got the above in my log also. But then it stopped reporting the error, and instead started to count strikes. So there might be a correlation. I believe it is a HW thing, and not with this program.

**Comment by chasut** [comment]
I think you are correct on that.  My guess, from reading through the community posts on the subject (and there are a lot of them) is that lightning must be very dependent on local conditions.  So some of the "screws" on the sensitivity settings are a bit too tight, and some too loose.  The AI must not yet be able to automatically do the calibration, or they just don't trust it enough to let it do so.  And/or there just may not be enough data points yet.  Unlike pressure or temperature, they just aren't frequent enough.

Of course, it could just be a bad unit/sensor.

They are very responsive, so hopefully they can get my fixed up.  There may be more to learn about how best to interpret the data that they do send, so will certainly let you know how it goes.  Very innovative approach, they are still learning as well.

**Comment by GlennGoddard** [comment]
I had the exact opposite problem, as you may have read in the forum.  I was getting several thousand strikes recorded a day but there was no lightning in reality for a thousand miles.

**Comment by chasut** [comment]
They just updated my station to v156.  They said it would fix my issue, so perhaps there is/was a known issue with the UDP lightning event.  Just need a little thunderstorm to test now.

**Comment by briis** [comment]
> Just need a little thunderstorm to test now.

Be carefull what you wish for, you might get it 😀

Sounds good. I will close this now, and if any of you find new issues with lightning, just create a new issue.
