### ISSUE TITLE
Dewpoint Comfort & Temperature Description

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#29]
For some reason sensors I have created for describing dewpoint comfort level keep progressing the number at the end of the sensor id during most Home Assistant updates lately.   For example sensor.dewpoint_description after a update (of HA) will be sensor.dewpoint_description_2.  This is not an issue with this component but a Home Assistant issue; however, including the description in the integration will save me time from having to change the same in all of my cards which can be cumbersome.  I currently have this pulled from my PurpleAir sensor and was going change it over the WeatherFlow sensors but I've had this issue with of few of my sensors that are created from other sensor, so it would be of benefit (me) to include them here.  Some components below don't apply but include for completeness.  I think I have include enough information.  Values below are in degrees fahrenheit.  I utilize the descriptions for notifications and some button cards.

Dewpoint Comfort Level Description:
```
purpleair_dewpoint_description:
  friendly_name: 'Outside Dewpoint Comfort Level'
  value_template: >
    {% if (states('sensor.purpleair_dewpoint')|float) >= 80.0 %}
      Severely High
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 75.0 %}
      Miserable
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 70.0 %}
      Oppressive
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 65.0 %}
      Uncomfortable
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 60.0 %}
      Ok for Most
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 55.0 %}
      Comfortable
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 50.0 %}
      Very Comfortable
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 30.0 %}
      Somewhat Dry
    {% elif (states('sensor.purpleair_dewpoint')|float) >= 0.5 %}
      Dry
    {% elif (states('sensor.purpleair_dewpoint')|float) <= 0.0 %}
      Very Dry
    {% else %}
      undefined
    {% endif %}
  entity_id: sensor.purpleair
  availability_template: '{{ not is_state("sensor.purpleair", "unavailable") }}'
```
Very Comfortable and Pleasant have been used interchangeably.

Temperature description:
```
purpleair_temperature_description:
  friendly_name: 'Outside Temperature Level'
  value_template: >
    {% if (states('sensor.purpleair_temp_2')|float) >= 104.0 %}
      Inferno
    {% elif (states('sensor.purpleair_temp_2')|float) >= 95.0 %}
      Very Hot
    {% elif (states('sensor.purpleair_temp_2')|float) >= 86.0 %}
      Hot
    {% elif (states('sensor.purpleair_temp_2')|float) >= 77.0 %}
      Warm
    {% elif (states('sensor.purpleair_temp_2')|float) >= 68.0 %}
      Nice
    {% elif (states('sensor.purpleair_temp_2')|float) >= 59.0 %}
      Cool
    {% elif (states('sensor.purpleair_temp_2')|float) >= 41.0 %}
      Chilly
    {% elif (states('sensor.purpleair_temp_2')|float) >= 32.0 %}
      Cold
    {% elif (states('sensor.purpleair_temp_2')|float) >= 20.0 %}
      Freezing
    {% elif (states('sensor.purpleair_temp_2')|float) <= 20.0 %}
      Fridged
    {% else %}
      undefined
    {% endif %}
  entity_id: sensor.purpleair
  availability_template: "{{ sensor.purpleair }}"
```

I don't have a sensor setup of UV descriptions yet, but those are easy:
Low 0 - 2.5
Moderate 2.5 - 5.5
High 5.5 - 7.5
Very High 7.5 - 10.5
Extreme 10.5 - 13

**Comment by briis** [comment]
So to make sure I understand you correct Glenn: You would like me to add the Level to this Integration? Would it be fine, if I add this as an Attribute to the Dewpoint and Air Temperature sensors?

**Comment by briis** [comment]
On further investigation, it will be very difficult to add this as Attributes, to Air Temperature and Dewpoint as they already get Max and Min Attributes and adding to this attribute set, realtime is not possible. So a better choice is to create 3 new sensors containing the value as their state. Are you OK with that? (I guess it is the same you do now anyway, just with template sensors)

**Comment by briis** [comment]
I made the new sensors and there is now a release 2.0.6 that adds these to your system. Please let me know if this was what you wanted, or if I did misunderstand it.

Btw.: There is one caveat with text based sensors: They work fine for you, as you have english as your native language, but I have not, so text based sensors are not really useful unless the text gets translated to native language. I think I will implement some kind of language handling in a future version.

**Comment by GlennGoddard** [comment]
Thanks, I did not think about translations.  I will test when I get back home.

**Comment by GlennGoddard** [comment]
Dewpoint description is off, I will check the code tomorrow.

**Comment by briis** [comment]
OK. I used your values and descriptions from above, so just let me know if those need corrections

**Comment by GlennGoddard** [comment]
My guess it is a metric / imperial issue; but I'm too tired to dive into right now.

**Comment by briis** [comment]
Maybe, but I convert Celcius to Fahrenheit, and use your Fahrenheit values as thresholds.

**Comment by briis** [comment]
YOU are right! As dewpoint is a calculated value, and I do that calculation before I get the Comfort Level, the value I send is already converted to Fahrenheit for you - so I convert it again. Easy fix.

**Comment by briis** [comment]
Should be fixed now with V2.0.7 - also implements Multi Language support and a new Beaufort Scale sensor.

**Comment by GlennGoddard** [comment]
Well....you beat me too it, that was one of my next ones, wind speed.
Guess I am working on the canvas gauge background for the Beaufort Scale today.

**Comment by briis** [comment]
I will close this now, as I believe it has been implemented.
