### ISSUE TITLE
Sea Level Pressure

### ISSUE THREAD

**Issue by JerLarge** [briis/hass-weatherflow2mqtt#3]
when comparing the HA smartweather integration to this (and the regular pressure)  a  sea level pressure of 5.88 hPa is not possible.   is there some conversion happening ? 

![image](https://user-images.githubusercontent.com/5440961/120029191-bf10a880-bfc3-11eb-9e1c-fb6976ecade1.png)

**Comment by briis** [comment]
Yes. Sea Level Pressure is not reported by the station. I will look at the formula. It works for metric.

**Comment by briis** [comment]
I couldn't see your picture and I can see now that you are running metric units.
I found the bug. When it is a tempest device, I have switched the temperature and station pressure when sending it to the conversion formula. I will fix it ASAP.

**Comment by JerLarge** [comment]
awesome.  not trying to be a pain or anything.   just wanted to point that out.
i had the elaborate node red setup  working, but it was flaky.   so far this seems fast, and stable.   i appreciate the developement!

**Comment by JerLarge** [comment]
corrected, and working as expected!

![image](https://user-images.githubusercontent.com/5440961/120030638-b91bc700-bfc5-11eb-8e51-8cb77016fc6f.png)

**Comment by briis** [comment]
Feel free to report anything you find. As I don't have a Tempest device I cannot test for little things like this.
A new Docker Container is build now, so if you make a new pull and replace the container it should be fixed. If it is working, just close this issue.

**Comment by briis** [comment]
You pulled it just before I could post the above :)

**Comment by briis** [comment]
It seems solved so I will close the issue.
