### ISSUE TITLE
Error with Temperature Description

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#31]
Just updated to the latest and realized I was not getting any updates.  Found these in my logs...
![Screen Shot 2021-06-24 at 12 23 06 PM](https://user-images.githubusercontent.com/42701104/123307085-af638180-d4e7-11eb-897e-0a8f9be52db8.png)

**Comment by briis** [comment]
Ups, a copy/paster error. I will fix ASAP.

**Comment by briis** [comment]
Pull the latest version and this is now fixed. (2.0.8)

**Comment by chasut** [comment]
Thank you, back up and running.  You are spoiling us with such fast turnaround!

**Comment by briis** [comment]
> You are spoiling us with such fast turnaround!

I know, this is dangerous 😗 I was just about to close the Computer for the day, and it was a fast fix.
