### ISSUE TITLE
Additional Lightning Sensors

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#32]
Now that my lightning sensor is (mostly) working and have been able to monitor through a small storm, I have a request to add to your backlog for consideration.  Apologies in advance, as I will be a bit long winded in and attempt am going to add detail around the my specific use-case.  Two additional lightning count sensors:

1. lightning_count -  Despite the description in the SmartWeather readme, in my implementation this sensor represents the number of strikes within 1 minute.  This turned out to be my favorite of the lightning count sensors in SmartWeather.  It gives a quick indicator of the intensity of the storm and a general read if it is increasing or decreasing.
2. lightning_count_last_1hr - For me, the 3hr increment is just too long.  I am sure it is different in other climates, but our storms come and go pretty quickly and many times in multiple waves.  Also, lightning strikes are numerous in those periods.  So I will get 60 strikes in just a few minutes, then the sky clears, sun comes out for a while, then the next storm cell comes through.. or not.  Net is that the 1hr increment feels more indicative of what is happening; sort of a compromise.  BTW, if I only get one, it would most definitely be the 1 minute resolution.

And just FYI.  I created a template sensor from the lightning_last_strike with relative_time() that when combined with the strike count gives a really good idea of if the storm is approaching or receding (they have this in the WeatherFlow app).  I am also thinking of using that handy derivative sensor that Glenn pointed me towards to create a rising/falling type sensor. 

Thanks

**Comment by briis** [comment]
I will look at it, as soon as I can.

**Comment by briis** [comment]
These are released in V2.0.15, so I will close this now.
