### ISSUE TITLE
Pressure sensor fail caused restart

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#33]
Twice last night my pressure sensor failed causing the container to restart.  Not a huge deal but figured you would want to look at the error handling.

It doesn't happen often, but that particular sensor does periodically report failure.  Best I can tell, it has happened four times total in the past two months.  They came in pairs, one right after another.  So really two incidents of two failures ~ 13 minutes apart.  I wouldn't have noticed if I hadn't been checking status of another container this morning.  Log entry of the first one attached:
![Screen Shot 2021-06-29 at 8 22 11 AM](https://user-images.githubusercontent.com/42701104/123806397-86126f00-d8b4-11eb-9f5f-541f34c2723f.png)

**Comment by briis** [comment]
Thanks. I will get some error handling done, so it does not break the container.

**Comment by chasut** [comment]
It caused the container to stop, but I have it set to automatically restart.  The container restarts quickly (less than a minute) and just picks up where it left off, so it is not easily noticed on the front end.  As long as it is set to automatically restart on failure, it has low impact on functionality, other than perhaps potentially missing some of the transaction data you are accumulating in storage.

**Comment by briis** [comment]
Fixed in latest version, so closing this.
