### ISSUE TITLE
Max/Min attributes not updating

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#35]
I have hit over 100F in the last few days but:

```
attribution: Powered by WeatherFlow2MQTT
brand: WeatherFlow
max_day: '98.8'
max_day_time: '2021-06-26T22:40:23+00:00'
max_month: '83.3'
max_month_time: '2021-06-26T01:28:46+00:00'
max_all: '83.3'
max_all_time: '2021-06-26T01:28:46+00:00'
min_day: '63.2'
min_day_time: '2021-06-26T12:36:55+00:00'
min_month: '52.0'
min_month_time: '2021-06-24T12:41:06+00:00'
min_all: '47.9'
min_all_time: '2021-06-19T12:19:07+00:00'
unit_of_measurement: ˚F
friendly_name: WF Temperature
device_class: temperature
```
Max all time and max month are less than max day, and max day is not updating.
Looks like the actual max for yesterday was 108.1F
Min does not match either

**Comment by briis** [comment]
I will need to investigate a bit more.

**Comment by briis** [comment]
I have been monitoring this for a while, and I believe I have to re-think how I do this. With the current approach I run some periodic updates, and if one of them does not run (For whatever reason), data can too easy get out of sync, and subsequent updates are no longer accurate. 

So I will work on a new approach - which might be a BREAKING CHANGE - but as it is now, data are not correct for a few of us, including myself.

**Comment by GlennGoddard** [comment]
Weird, the Min and Max were spot on yesterday.  Today they are still yesterday's values and off.

**Comment by briis** [comment]
If the Midnight Process is not running at the correct time (For whatever reason) this will be off. So I need to figure out a more robust way of ensuring this is done.

**Comment by GlennGoddard** [comment]
I check for updates to the docker images I have regularly, so I updated yesterday to the latest release.
When I updated, it stopped sending anything to MQTT; I restarted a few times with no results.
I had to completely clear all files in the config directory and then it worked.

I don't know if you intended the last update to be for public consumption or not.  I also, don't know if it had breaking changes (at least for some).

I did see my new temporary high and low at 999 and -999; they appear to be tracking now.

**Comment by briis** [comment]
@titilambert refactored the structure and it took a few iterations for me to ensure that it worked. My tests show that everything is working now. I also tried to build the image for different platforms, so that people using ARM also can pull it directly. The images are pushed to Docker Hub instead of Github. Could I get you to try and pull the latest image from there? Use `briis/weatherflow2mqtt:latest` instead of `ghcr.io/briis/hass-weatherflow2mqtt:latest`. Remember to delete the current image, before you do it.

**Comment by GlennGoddard** [comment]
Pulled new image from docker hub.  Everything appears to be working but it is just after midnight here.  I will monitor and let you know.  I also modified my docker pull script to pull from the new repo.

**Comment by briis** [comment]
Thanks Glenn. Just tested it on my Synology, a PI3 and Intel NUC, and I also get it working. Let me know how it goes.

**Comment by GlennGoddard** [comment]
Min Max daily appear to be working well.  They match the app history and the 24hr graph in HA.

**Comment by GlennGoddard** [comment]
Ok, new observation.  The max and min are now max and min for the last 24hr and not reset at midnight as far as I can tell.
Is this what you indended?  I actually like the last 24hr period over reset at midnight.

**Comment by GlennGoddard** [comment]
Closing issue, since everything appears to be resolved now.
