### ISSUE TITLE
Error collecting device status

### ISSUE THREAD

**Issue by titilambert** [briis/hass-weatherflow2mqtt#37]
```
DEBUG:__main__:DEVICE STATUS TRIGGERED AT 2021-07-05 11:55:28.313845
 -- Device: ST-00028410
 -- Firmware Revision: 156
 -- Voltage: 2.75
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/tcohen/perso/gits/github.com/briis/hass-weatherflow2mqtt/weatherflow_mqtt.py", line 499, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tcohen/perso/gits/github.com/briis/hass-weatherflow2mqtt/weatherflow_mqtt.py", line 361, in main
    device_status = await cnv.device_status(sensor_status)
  File "/home/tcohen/perso/gits/github.com/briis/hass-weatherflow2mqtt/helpers.py", line 394, in device_status
    return_value.append(DEVICE_STATUS[len(binarr)-x])
IndexError: list index out of range
```
I run it locally and in docker, I got the same error.
I was able to run a pdb to know the value of some variables:
* `binarr: '100000000000000000'`
* `DEVICE_STATUS: ['Sensors OK', 'lightning failed', 'lightning noise', 'lightning disturber', 'pressure failed', 'temperature failed', 'rh failed', 'wind failed', 'precip failed', 'light/uv failed']`
* `return_value: []`
* `value: 131072`
* `x: 0`
* `len(binarr)-x: 18`

Note: Hub firmware release: 170

So I guess something is missing in the `DEVICE_STATUS` list ?

**Comment by briis** [comment]
Thanks for reporting. I don't think I miss something, there is just something screwed up with my code, trying to de-construct the binary. I will look at it as soon as I can.

**Comment by titilambert** [comment]
hum, 
I just found this: https://weatherflow.github.io/Tempest/api/udp/v143/

For device status, it says:
```
any bits above 0b100000000 are reserved for internal use and should be ignored
```

So maybe we should just do nothing is x > 10 ?

**Comment by briis** [comment]
Yes, that might be the fast solution. Let me look at it tonight or tomorrow morning.
