### ISSUE TITLE
Repo structure refactoring (add setuptools)

### ISSUE THREAD

**Issue by titilambert** [briis/hass-weatherflow2mqtt#39]
Hello @briis 
Would you be willing to accept a PR which refactors the structure of the repo to use python setup tools ?
It will help to manage dependencies and add some unit tests

**Comment by briis** [comment]
Yes, thank you. I am totally self-taught on this, so whatever you can do, I can learn from. So please go ahead. I might ask some questions to understand what/why you are doing, but I look forward to learn.

**Comment by briis** [comment]
Hi Thibault,
As you know I merged this, so thanks again. I had to re-add the VERSION file, as this is used in the Github Actions, to autobuild the Container.

I tried however to build the container for the ARM/V7 platform using the docker buildx command, and I am getting the below error. (That worked before the refactoring). It seems it is missing the gcc program, but I am not completely sure how to get that included.

````
#13 139.1   building 'yarl._quoting_c' extension
#13 139.1   creating build/temp.linux-armv7l-3.9
#13 139.1   creating build/temp.linux-armv7l-3.9/yarl
#13 139.1   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c yarl/_quoting_c.c -o build/temp.linux-armv7l-3.9/yarl/_quoting_c.o
#13 139.1   error: command 'gcc' failed: No such file or directory
````

**Comment by titilambert** [comment]
Hello,
It's just because I set `FROM python:3.9-slim-buster` instead of `FROM python:3.9-buster`
If you change that in the Dockerfile, everything should be good. 
(I did that in order to reduce the size of the docker image)

**Comment by briis** [comment]
Thanks. I think I will change it back, because then I can build for all Platforms, and then just change the reference to docker hub instead.

**Comment by briis** [comment]
Again thanks for your help on this. I will close this issue, as all seems to be working now.
