### ISSUE TITLE
Keyerror 'Icon' caused container to restart

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#44]
Found a series of these in my logs, all 9-20 seconds apart, causing the container to restart.  Seems to have subsided for now.  Perhaps it found a condition that it did not anticipate.  Unfortunately I don't have any more information to offer.

![Screen Shot 2021-07-10 at 7 58 18 PM](https://user-images.githubusercontent.com/42701104/125179946-b2ce5c80-e1b9-11eb-8120-b8f8eff793bb.png)

**Comment by briis** [comment]
Thanks. I will double check that all the icons are correct.

**Comment by briis** [comment]
It has been impossible for me to reproduce this error. But I now added better error handling, and logging of the value received, so that it will be easier to debug if it happens again. I am closing this now.
