### ISSUE TITLE
Add docker-compose details

### ISSUE THREAD

**Issue by crzykidd** [briis/hass-weatherflow2mqtt#45]
I converted the docker run to docker-compose format.   I can add it to the Readme with a PR or save it as a docker-compose.yml file if you want?   Here are the details:

`version: '2'
services:
  weatherflow2mqtt:
    image: ghcr.io/briis/hass-weatherflow2mqtt:latest
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - TEMPEST_DEVICE=True
      - UNIT_SYSTEM=imperial
      - LANGUAGE=EN
      - RAPID_WIND_INTERVAL=0
      - DEBUG=False
      - ELEVATION=0
      - WF_HOST=0.0.0.0
      - WF_PORT=50222
      - MQTT_HOST=
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_DEBUG=False
      - ADD_FORECAST=True
      - STATION_ID=
      - STATION_TOKEN=
      - FORECAST_INTERVAL=30
    volumes:
      - /YOUR_STORAGE_AREA/PATH:/usr/local/config
    ports:
      - 0.0.0.0:50222:50222/udp`
Let me know if you want me to do a PR for this?

**Comment by briis** [comment]
THANK YOu. Please create a docker compose file, and add this in a PR if possible. And also update the readme on how to use it.

**Comment by crzykidd** [comment]
Will do this weekend

**Comment by GlennGoddard** [comment]
@crzykidd Did you get this in a compose file?

**Comment by crzykidd** [comment]
A PR has been created #59.   Sorry for the delay.

**Comment by briis** [comment]
PR merged. Closing this now. Thank you.
