### ISSUE TITLE
No obs_sky messages

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#49]
With the last update I do not get any obs_sky messages to MQTT.
I appear to have everything else but since the actual data is all in obs_sky, I don't have much into HA.

Looks like it is related to my last PR.  I passed temp and dewpoint_c so I'm not sure what happened.
```

DEBUG:weatherflow2mqtt.weatherflow_mqtt:Event type device_status has been processed, with payload: {}


Traceback (most recent call last):


  File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>


    sys.exit(load_entry_point('weatherflow2mqtt==0.10.0', 'console_scripts', 'weatherflow2mqtt')())


  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-0.10.0-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main


  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run


    return loop.run_until_complete(main)


  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete


    return future.result()


  File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-0.10.0-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 305, in main


TypeError: visibility() missing 2 required positional arguments: 'temp' and 'dewpoint_c'


DEBUG:asyncio:Using selector: EpollSelector
```

**Comment by briis** [comment]
I am on a short vacation, back Friday. So I cannot look at it before then.

**Comment by GlennGoddard** [comment]
Looks like someone already did a PR for this.

**Comment by briis** [comment]
I can merge the PR now, but I cannot build the docker images. before I am back home. So you can try and build yourself, and see if that works.

**Comment by GlennGoddard** [comment]
Your latest push fixed most of the data not getting thru; however the visibility is now zero.
The last PR I looked at passed temperature vice temp and dewpoint vice dewpoint_c, I don't know if that is the issue.  I just looked at what changed but did not look at how that is passed.  I passed to the visibility function; I need to dig into what the other passing of variables was that I missed the first time.

**Comment by briis** [comment]
I noticed the same. I already changed the procedure, to pass temp and humidity (to ensure it always in Metric), and then calculate the dewpoint in the visibility function. All that seems to work, but the state never gets published, even though the calculation runs without errors. And with no state published no value in HA. I am looking in to that right now.

**Comment by briis** [comment]
So, I made v2.0.12, which I believe fixes the issue. Could you try that?

**Comment by GlennGoddard** [comment]
I will check it when i get back home; that will be a few hours.

**Comment by GlennGoddard** [comment]
I looked at the code, and I'm confused.  Was dewpoint_c not available and had to be calculated inside the function again?

**Comment by briis** [comment]
Yes, it was calculated, but if you use it with Imperial units set, the dewpoint function returns the value in F and so does the temperature function, so the formula you made would have to be changed, for Imperial Units. I found it easier just to recalculate dewpoint, and ensure the value was returned in metric units for dewpoint.

**Comment by GlennGoddard** [comment]
I might rework the function a little.  For clarity, I was thinking of breaking the components up such as the max possible distance and then then percent of that for humidity effects.  I think this would be helpful since I have some other formulas I'm working on based on light levels.

**Comment by GlennGoddard** [comment]
It is working well.  Visibility approximation calculation seems to be tracking fairly well with weather sites.
With this, I may have figured out a big part of the fog calculation by having visibility as one of the conditions.
