### ISSUE TITLE
Delta T off

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#51]
I don't normally look at Delta T, so I don't know when it went wonky.
Per HA the delta T is -43.2F which is impossible (under most conditions), and the app reports 9.7F.

I don't know if this is limited to just us non-metric users or if this is an issue for metric also.

Air Temp, Wet Bulb Temp, Dew Point, Humidity all track, so it appears to be a calculation in Delta T.

Documenting for now, I will look at the code after I change out some light switches.

**Comment by GlennGoddard** [comment]
Is 'temp' always in Celsius or does it change depending on imperial or metric.
I think it is always in Celsius, that is what I assumed in the visibility calculation.
If it is always in Celsius then the Delta-T function is off since it assumes it changes based on metric or imperial.

For me it looks like that temp is in Celsius and then the self generated wetbulb is in Fahrenheit and thus a negative number is generated as a return.

I will go with the assumption that temp is always in C and make a PR based on that.

**Comment by GlennGoddard** [comment]
PR submitted

**Comment by briis** [comment]
I always assume that the raw data we get from the station is in metric values, and it seems to be like that. I will look at the PR now.

**Comment by GlennGoddard** [comment]
Still off, not negative thou.
App 8.5, HA 40.5

All the bouncing back for metric and imperial makes the code a little confusing

**Comment by briis** [comment]
Yes it does. But I have found the error now, and it is fixed. Will be out in the next release.

**Comment by GlennGoddard** [comment]
Visibility is acting funky.  Don't know if it is related or not.  I will rework this so there is only metric formula and the imperial is just a conversion from the metric.  Are you making changes directly and not doing a PR, just asking since I can't seem to see changes you've made recently (as in comparing them); nothing wrong with that, just asking.

**Comment by robertw** [comment]
as reported by tempest software 
Delta T
1.4 °F

WF Delta T
1 minute ago
33.5 ˚F

Something looks off just a fyi

**Comment by GlennGoddard** [comment]
He just identified the issue, it has not been resolved yet.  Won't be till Sunday that he gets this done.

**Comment by robertw** [comment]
I am so not as well versed as you guys just reporting thank you all for your hard work truly appreciated

**Comment by GlennGoddard** [comment]
@robertw 
Any other issues, please feel free to report.  The more eyes looking at something, the greater the chance to make it  better.
FYI, the visibility calculation is a little of and I hopefully corrected it in the pending change.

**Comment by briis** [comment]
This is released in 2.0.15. Please let me know if it is still OFF. Closing for now, but just reopen if needed.
