### ISSUE TITLE
Newst build Docker on linux, arm64 home assint 

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#54]
this error is coming up 

have 
forecast = true

Error parsing value: 'value_json' is undefined (value: off, template: {{value_json.state}})
7:56:16 AM – (ERROR) helpers/template.py - message first occurred at 7:56:15 AM and shows up 200 times
Template variable error: 'value_json' is undefined when rendering '{{value_json.state}}'
7:56:16 AM – (ERROR) helpers/template.py - message first occurred at 7:56:15 AM and shows up 200 times

**Comment by briis** [comment]
And how are you sure this is generated from this integration?

**Comment by robertw** [comment]
My mistake sorry did not realize i had one other device reporting to mqtt  please disregard .....
