### ISSUE TITLE
Consider a testing Docker tag

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#57]
Do you think it would be beneficial if you have a docker build for testing that is not in the latest?  This would allow some of us to test changes before it is released in to the latest and also to easily fall back if it doesn't work.

Or you could do the testing under latest as it would be the latest and have a stable tag for the good release before and move latest to stable once there is feedback on the latest.

**Comment by briis** [comment]
A good idea. I could do -dev release for new stuff. 

But I am away again this week, so I will not do a lot during the week. Back Sunday.

**Comment by GlennGoddard** [comment]
The one thing I am not sure about is if the latest tag will pick up the most recent whether it is a dev release or a stable one.
We can test this with the PR I just did.  Put the dev tag on it and we can see if the latest tag gets applied or not.

I'll check the results when you get back.

**Comment by briis** [comment]
So in the future, I will push all development stuff, to a new tag called `dev`. I will push to this every time I build, but if things are not tested, I will only push to this, leaving the `version` number tag and `latest` untouched until everything works.

**Comment by GlennGoddard** [comment]
Let me know as soon as you put up something with the dev tag.  I just tried and dev not found.

I 'might' have the battery PR ready in a few days depending on work load (or at least ready for some review).  The bulk is ready for the actual sensor but not the MQTT or passing data to part.

**Comment by GlennGoddard** [comment]
So, would you delete the dev tag when it passes to the latest or have it in both?

**Comment by briis** [comment]
I will post here when there is something in the dev tag. I will not delete the tag, so if you always want to run the latest version, no matter if it is a released version, you can follow the dev tag.

**Comment by briis** [comment]
As said, the `dev`tag is the testing tag, and will always have the latest published release. If datetime is the same as the `latest` tag, then there is not a new dev version available.
But if you are happy with the latest - maybe untested - version, then use the `dev` tag to always be on top.

**Comment by GlennGoddard** [comment]
dev tag works, everything appears to work for the Tempest

**Comment by GlennGoddard** [comment]
What do you think about creating a stable branch on GitHub once a dev image passes that way it will be easier to revert to a known good code?
So basically, only update the stable branch from main once testing is good for dev build.

**Comment by briis** [comment]
Good idea. Now done, with the latest release, which seems to be pretty stable.
