### ISSUE TITLE
Retain all states?

### ISSUE THREAD

**Issue by cmsimike** [briis/hass-weatherflow2mqtt#58]
I've noticed that after restarting Home Assistant, many values are unknown until the next update for those values, sometime I've notice that might be a while. For instance:
![image](https://user-images.githubusercontent.com/204378/127070592-fd04102c-8869-411c-852c-18c152903cb8.png)

Is it possible to `retain` these messages so that Home Assistant shows some data in this case? Or am I doing something wrong here?

**Comment by GlennGoddard** [comment]
It should populate everything within a few minuets.
Load up MQTT Explorer and see how long it takes to get your messages.
Stop the weatherflow container, load up MQTT Explorer, start weatherflow container and see how long it takes.

**Comment by GlennGoddard** [comment]
What is the voltage of your station?
If the battery is low it will change the times between reports.
[https://community.weatherflow.com/t/tempest-battery-voltage-range/6120/2](url)

**Comment by cmsimike** [comment]
Thanks for the reply!

I had MQTT Explorer up for about 5 minutes. Most topics started with 2 messages. Only a couple of them got messages as I waited (the topics with more than 2 messages). The rest didn't get updated in the length of time I waited.

![image](https://user-images.githubusercontent.com/204378/127244790-0c792a32-b9c1-492e-aff7-f376046c9141.png)

According to hass, voltage is 2.57 (range is 2.56-2.58)
![image](https://user-images.githubusercontent.com/204378/127244838-3add3f49-abc7-4372-89d4-375d24a04623.png)


The link you gave me (copied and paste) is 404 so I don't know what the voltage value should be.

Let me know if I missed anything!

**Comment by GlennGoddard** [comment]
I didn't put the link in twice, but if you select, copy and paste it will take you to the WeatherFlow Forums; or click below it should work now.
[https://community.weatherflow.com/t/tempest-battery-voltage-range/6120/2](https://community.weatherflow.com/t/tempest-battery-voltage-range/6120/2)

**Comment by cmsimike** [comment]
Do you have to be logged in:

![image](https://user-images.githubusercontent.com/204378/127251979-af273126-161a-4868-9170-c3e98e41e2b1.png)

**Comment by cmsimike** [comment]
FYI I tried logging in and still got the above page.

**Comment by GlennGoddard** [comment]
Hum, link worked for me.

Here is the info:

Power Modes
Mode 0

Voltage >= 2.455

Full power all sensors enabled
Mode 1

Voltage <= 2.415 or >= 2.41 from Mode 2

Rapid sample interval set to six seconds
Mode 2

Voltage <= 2.39 or >= 2.375 from Mode 3

Rapid sample interval set to one minute
Mode 3

Voltage <= 2.355

Rapid sample interval set to five minutes

Sensor sample interval set to five minutes

Lightning sensor disabled

Haptic sensor disabled

**Comment by cmsimike** [comment]
Cool, so according to the above, my Tempest should be at full power/mode 1.

So I guess back to the original question, I feel like the updates from the tempest don't happen as quick as expected, and home assistant then shows unknown during that period. For instance, the last time I restarted home assistant, it was about 1 hour before all the sensors were populated with data. Only the mqtt topics with messages  > 2 ended up having values come in quick.

**Comment by robertw** [comment]
just toss my 2 cents in are you getting a strong signal form the base unit to the receiver ? tempest app update in real time?

**Comment by GlennGoddard** [comment]
Next time your restart HA, restart this container also so it can repopulate the sensor template data via MQTT to HA.

**Comment by cmsimike** [comment]
@robertw Connection seems fine, according to the app (reading RSSI).

@GlennGoddard I'll have to keep an eye on it further but I allowed the weatherstation to connect to the internet and restarted hass a bit after, and the values populated quickly. I don't know if it's by chance or what but I'm going to keep an eye on it.

Looking back at my hass history, the entities that don't populate right away all have periods where no data shows up (even with hass running), so now I'm wondering if a firmware update (now that I am allowing it on the internet) fixed the reporting issue.

Regardless I don't think this issue is relevant anymore so I am going to close it. Thanks for the help! If i notice anything else I can open another issue.

**Comment by cmsimike** [comment]
To quickly follow up, after allowing my Tempest to connect to the internet, the data stream seems a lot better. I am getting constant updates now vs before where some values like Dew Point wouldn't update for a couple hours before picking back up.

I don't know if there's some weirdness with keeping it disconnected on the internet or if a firmware update fixed something, but the issue seemed to be the device itself.

**Comment by GlennGoddard** [comment]
Have you tried blocking it from the internet and seeing what happens not to see if it was just firmware?

**Comment by cmsimike** [comment]
Not yet, I was planning on it (and I'll get back to you with the results) but I wanted to let it play out for a few days to see if the issue comes back. I'll let you know when I've tested it again.

**Comment by cmsimike** [comment]
So I left the Tempest connected to the internet since that comment and never had an issue of Tempest not reporting values. This afternoon I disconnected it from the internet and basically instantly stopped reporting some values (not the flat line):

![image](https://user-images.githubusercontent.com/204378/127944891-2cc60a61-d22b-43d3-8ab7-d90e0185a330.png)

**Comment by cmsimike** [comment]
The second I allowed it on the internet, it started reporting values. Interestingly, the value of Dew Point started to jump around wildly
![image](https://user-images.githubusercontent.com/204378/127945037-dd5adeb6-c3d1-4a58-8e7d-14237afad597.png)


I wonder if Tempest tries to keep values if it isn't connected to the internet? The behavior I was seeing once it connected showed erratic values.

**Comment by GlennGoddard** [comment]
I'm going to have to test this myself when the kids are not devouring the internet.  Everything is UDP except the forecast, there might be an error handler that went wrong.

**Comment by GlennGoddard** [comment]
Well I got the opportunity to test this since my internet went down last night.  With no internet connection I get all the values from the tempest (except current conditions which is cloud based).

How where you isolating it from internet?

**Comment by cmsimike** [comment]
I have a rule on my firewall that drops any packet out of the iot network (which the tempest is connected to).

Just to be clear, while not connected to the internet, I did get all non-cloud based messages for a while. It was very much hit or miss - there would be multiple hours where I would get data then about one-two hours of not getting data (based on what I was seeing in the hass history)

Suddenly not getting tempest updates when I removed it from the internet might be happenstance. I think to get a better test would be (and I am not suggesting you do this because it's probably annoying) would be to keep it disconnected from the internet for a few days and see if your hass history ever goes flat for certain sensors.

**Comment by GlennGoddard** [comment]
My internet was down for about 8 hours and I have changing data from my Tempest.  I wonder if your switch is not passing the UDP traffic because of the firewall rules.  UDP does originate from an IP so it could technically happen.

Do you have a few routers and then then your internet access point?  Is there a way you could run something like wireshark sniffing UDP on the same router as the WeatherFlow hub and also on the network effected by firewall rules?

**Comment by briis** [comment]
Just my few cents on this: The only thing that the Internet is used for is the Current Conditions and Forecast Data. If you have not enabled that feature, then all runs locally. All the calculated sensors are build with data coming from the UDP Broadcast - so if UDP works, and you are not using the the Forecast piece, then the only point of failure, could be the MQTT Server.

**Comment by cmsimike** [comment]
Sorry for the delay in this. I have been afk.
My switch isn't doing the filtering, the firewall is. Packets destined for the same network never leave the switch. If it was a firewall (or something) rule dropping the packets then I don't think I'd get any data.
