### ISSUE TITLE
hail and heavy rain 

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#60]
Just a quick point we live in south Florida system says hail when it is heavy rain ,,,

**Comment by GlennGoddard** [comment]
The rain / hail sensor is direct from the tempest and not a calculated point.
Out of curiosity do you have the rain rate when you see this?
What does the WeatherFlow app say about the precipitation type?

**Comment by robertw** [comment]
the app  says heavy and yes it is raining lol......hard

**Comment by GlennGoddard** [comment]
Can you post screen shots of the app and what you get in HA?
Might have to post in either the HA or WF forums for the pics (easier)

**Comment by robertw** [comment]
I will ......

**Comment by GlennGoddard** [comment]
I grew up in central Florida, everyday at 1500 (3pm) it would rain for about 15 mins.
I the app says heavy that means it is getting a '3' from the Tempest which is either Rain+Hail or Heavy Rain.  But a '2' is hail.
WF did just announce they pushed some changes out yesterday.
I will look to see if they updated the UDP API guide and see there are changes.

**Comment by robertw** [comment]
i am on 170 on the hub and 156 on the unit

**Comment by GlennGoddard** [comment]
They did not post any updates to the API.  What is weird is that you get Hail in HA but heavy in the app.  Only mention of a change regarding rain is the image in the app.
Post the shots when you get them.
Is this a common thing, recent, or just noticed?

**Comment by robertw** [comment]
No it's been since I've been trying the program it's never been correct

**Comment by robertw** [comment]
#
![Screenshot_20210802-151232_Chrome](https://user-images.githubusercontent.com/725783/127911731-f3a200dd-5261-4e0e-a787-76ad38a72757.jpg)
![Screenshot_20210802-151227_Chrome](https://user-images.githubusercontent.com/725783/127911732-b86151f7-5760-4312-91f2-e6b7e9d93f0b.jpg)
![Screenshot_20210802-151220_Chrome](https://user-images.githubusercontent.com/725783/127911734-f872396c-081c-4fb8-9043-196945d11ea4.jpg)
![Screenshot_20210802-151200_Chrome](https://user-images.githubusercontent.com/725783/127911737-d593ffa7-2f1b-4ff4-bfe7-b45de58d3cb5.jpg)
![Screenshot_20210802-151145_Tempest](https://user-images.githubusercontent.com/725783/127911738-08e6bca9-c341-4a66-8d01-e8b7b5d5af7d.jpg)

**Comment by robertw** [comment]
I was able to grab these it just happened as you can see tempus says heavy

**Comment by briis** [comment]
The data we get from the station is a Bit value. From the UDP Documentation:

`0 = none, 1 = rain, 2 = hail, 3 = rain + hail (experimental)`

I renamed the bitvalue 3 to Heavy Rain, based on pure observation from my Window - every time I got a bit value 3, it was not hailing, but Heavy Rain. Happy to modify the text?

**Comment by robertw** [comment]
I believe they use the word heavy to cover all basis not heavy rain thats all I was trying to show thank you for the change since we live in south Florida hail is not very often but it does happen lol......

**Comment by briis** [comment]
Thanks. I will rename it to Heavy (without the Rain) Makes sense to me, and covers all bases.
