### ISSUE TITLE
add Wet Bulb Glob Temperature (WBGT)

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#62]
This is a way to show heat stress on the human body.
I have already started working on this.
Need to estimate Black Globe Temperature, some methods would require sun azimuth.  I know Astral library can do this but I'm looking into other ways, but may still end up with Astral.
[https://www.weather.gov/tsa/wbgt](https://www.weather.gov/tsa/wbgt)

**Comment by GlennGoddard** [comment]
I found a close approximation that does not require sun azimuth.
WBGT = 0.7Twb * 0.2Tg * 0.1Ta
where
WBGT is Wet Bulb Globe Temperature in C
Twb is Wet Bulb Temperature in C
Tg is Black Globe Temperature in C
Ta is Air Temperature (dry bulb)

Tg = 0.01498SR + 1.184Ta - 0.0789Rh - 2.739
where
Tg is Black Globe Temperature in C
SR is Solar Radiation in Wm^2
Ta is Air Temperature in C
Rh is Relative Humidity in %

So...do we want Black Globe Temperature as an additional output, my initial guess is no.  So.
WBGT = 0.7Twb * 0.2 * (0.01498SR + 1.184Ta - 0.0789Rh - 2.739) * 0.1Ta
This can be simplified but works like this.

I will work on a PR to calculate it but will let @briis add the MQTT naming conventions and output.
I will do all work in Celsius and then just do a conversion for Fahrenheit (I think you already have a function for this but easy if you don't)

**Comment by GlennGoddard** [comment]
@briis I need your help in pulling in Solar Radiation into helpers.py

**Comment by briis** [comment]
If you create a new function in `helpers.py` that does the above calculation, you can pass `obs[11]` in the Tempest section to that formula, this contains the solar radiation value. I will need to add that to the AIR&SKY section also.

Does this help?

**Comment by GlennGoddard** [comment]
Do the Air & Sky have solar radiation?

**Comment by briis** [comment]
Yes, they have the same sensors as the Tempest device, data is just retrieved a bit different and with different Index the Arrays

**Comment by GlennGoddard** [comment]
The air does not have solar radiation in weatherflow_mqtt.py unless it uses the sky event???
I see:
sky obs[10]
tempest obs[11]

**Comment by GlennGoddard** [comment]
#69

**Comment by GlennGoddard** [comment]
FYI, I had wbgt commented out in the Sky and Air sections of weatherflow_mqtt.py.  I was not sure which section to add it too.
Function looks good, thanks for catching that mistake.
I did not add this to const.py, since I am not sure of the layout.

It will be about 12 hours before I can test.

**Comment by briis** [comment]
> FYI, I had wbgt commented out in the Sky and Air sections of weatherflow_mqtt.py

I saw that. The issue for AIR&SKY users is that most needed values comes from the AIR device, but Solar Radiation comes from SKY. So what I do is that I store the Solar Radiation in a Variable when data is received, and the I only process the function when the AIR device is sending data. I set the initial value of the var to None, so that the function just returns a None value until we have the Solar Radiation.

> I did not add this to const.py, since I am not sure of the layout.

No worries. I have done all the necessary work to create the sensor. 

Just let me know when you have tested.

**Comment by GlennGoddard** [comment]
Working so for Tempest, will need 24 hours to verify since no solar radiation at this time.

**Comment by briis** [comment]
How did this go? Is it giving you the expected result?

**Comment by GlennGoddard** [comment]
So far, but it has been completely overcast/night/overcast since I updated.
It is outputting a good number.  I feel good closing this, if I need to tweak the function I will do that later when I have good data from what we have first.

I am in the process of making a background for WBGT flag colors at the moment (to the canvas gauge).  I like how simple it is to interpret the information with a colored background.

[https://github.com/GlennGoddard/CanvasGaugeBackgrounds](https://github.com/GlennGoddard/CanvasGaugeBackgrounds)

**Comment by GlennGoddard** [comment]
Did you add this to air & sky?

**Comment by briis** [comment]
Yes. Look at line 252 in `weatherflow_mqtt.py`. The only difference is that it might take up to 2 updates of the devices before the value is calculated, because we need to get the solar radiation from the SKY device.

**Comment by briis** [comment]
The Canvas Backgrounds look great - I have just bought a new House, so I will not really do a lot with my UI for the next 6 month, as I plan to start all over when I move. But then all the fun begins 🤣

**Comment by GlennGoddard** [comment]
I will add those to the readme along with the battery and voltage info.
Need to update the sensor list below the chart also, I forgot about that until I looked at it earlier today.
