### ISSUE TITLE
add battery percentage

### ISSUE THREAD

**Issue by GlennGoddard** [briis/hass-weatherflow2mqtt#63]
This can be on the bottom of the list but due to the way Home Assistant displays MQTT integrations it assumes there is a battery that is reported in percentage, and it means more at a first look than the voltage alone.
For now I am ignoring the operating modes of the tempest based on battery voltage, although I can see setting a if...then for percentage if it is in the range of each mode.
Battery range is 1.8 to 2.85Vdc
Anything > 2.85 is capped at 100%
Anything < 1.8 is capped at 0%
P = (V - 1.8)/1.05
where:
P is percentage
V is battery voltage
This is a very simple calculation but can be estimated to be simplified more and is still fairly accurate to either:
P =  V - 1.8 or P = V - 1.85
either is within an acceptable range between them.
The first of the three is the most accurate but any are acceptable

I don't know how to pull in to helpers.py so I set 50% of it up and let you take care of the MQTT bit also.  I'm sure if I looked around the code enough I could figure it out but I also don't want to step on your toes by introducing names outside of what you want for naming conventions.

**Comment by GlennGoddard** [comment]
Ok, I think I figured out how to send the information into helpers.py from weatherflow_mqtt.py.
When I get the time at home, I will in the container and make the changes locally to see if everything checks out.

**Comment by GlennGoddard** [comment]
'''
# helpers.py

    async def battery_level(self, battery):
        """Returns the battery percentage.
           Input:
               Voltage in Volts DC
		   Battery voltage range is 1.8 to 2.85 Vdc
		       > 2.85 is capped at 100%
		       < 1.8 is capped at 0%
        """
        if battery is None:
            return None

        if battery > 2.85:
            # Cap max at 100%
            pb = float(100)
        elif battery < 1.8:
            # Min voltage is 1.8
            pb = float(0)
        else:
		    # pb = (battery - 1.8)/1.05
		    # Multiply by 100 to get in percentage
            pb = float((voltage - 1.8)/1.05*100)

        return round(pb, 0)
'''

# weatherflow_mqtt.py

**Comment by briis** [comment]
Hi Glenn,
I would suggest that percentage would be the `state` of the sensor, and then Voltage could be added as an attribute. Would that make sense to you?

This is however a bit more complex than above. My Tempest unit for example, has never been above 2.81V so that seems to be my max, here in the cold Nordics. But I also have a Sky and AIR Unit, and they run above 3V when fully charged. So the formula needs to be a bit more complex, with some spans on the Voltage and separate formulas for Tempest and AIR & SKY.

**Comment by GlennGoddard** [comment]
I will see what I can come up with for the Sky and Air units for their respective batteries.
I did see that some Tempest have a max battery of 2.85 and others at 2.8; I figured setting it at 2.85 would still be good for most since that would give you 96% still; or I could cap it at 2.8 or 2.81 either would still be more useful (in my opinion) than the voltage alone.

**Comment by briis** [comment]
You could just set everything >= 2.80 as 100% for a Tempest Device, and then let it start going down from 100 when below that.

**Comment by GlennGoddard** [comment]
2.8 is a very convenient max since just subtracting the low of 1.8 gives the percent without any other division.

*** Work in Progress, I will be editing this before putting into PR ***

# helpers.py
```
async def battery_level(self, battery):
    """Returns the battery percentage.
       Input:
           Voltage in Volts DC
           Tempest:
	     Battery voltage range is 1.8 to 2.85 Vdc
	         > 2.80 is capped at 100%
	         < 1.8 is capped at 0%
          Air:
             4 AA batteries (2 in series, then parallel for 2 sets)
	     Battery voltage range is 1.2(x2) => 2.4 to 1.8(x2) => 3.6 Vdc
	         > 3.6 is capped at 100%
	         < 2.4 is capped at 0%
          Sky:
             8 AA batteries (2 in series, then parallel for 4 sets)
	     Battery voltage range is 1.2(x2) => 2.4 to 1.8(x2) => 3.6 Vdc
	         > 3.6 is capped at 100%
	         < 2.4 is capped at 0%
    """
    if battery is None:
        return None

    if is_tempest:
         if battery > 2.80:
             # Cap max at 100%
             pb = float(100)
         elif battery < 1.8:
             # Min voltage is 1.8
             pb = float(0)
         else:
	      # pb = battery - 1.8
	      # Multiply by 100 to get in percentage
             pb = float((voltage - 1.8)*100)
   else:
         if battery > 3.60:
             # Cap max at 100%
             pb = float(100)
         elif battery < 2.4:
             # Min voltage is 2.4
             pb = float(0)
         else:
	      # pb = (battery - 2.4)/1.2
	      # Multiply by 100 to get in percentage
             pb = float(((voltage - 2.4)/1.2)*100)

    return round(pb, 0)
```
Should I have this with a decimal of precision or just make it an integer?  I initially rounded the float to 0 but I think an integer would make more sense, what do you perter?

**Comment by briis** [comment]
I think Integer is the right precision, as percentages with decimals are rarely used.

**Comment by GlennGoddard** [comment]
Can you look at your battery history for your Air & Sky to see if the ranges make sense?  I looked through posts on the forum and think I have a good range.  I do know that the voltage range would drop (both upper and lower limits) if using rechargeable batteries, but I think this range will still give a value add.

I have this as Battery branch in my fork, I have only got helpers.py done at this time (exactly what is above).

**Comment by briis** [comment]
These devices have been Offline since I swapped with my Tempest Unit. I just checked the last reported Data, and I believe your range is pretty good. My SKY Unit was running on rechargeable and that was on 3.46V, so maybe 3.60 is pretty high for the upper limit. 3.50 might be better.

**Comment by GlennGoddard** [comment]
Not sure how to handle the battery level for Sky, Air, and Tempest since Tempest shares event types and all three have different locations for battery level.  Unless I can put is_tempest in the EVENT_AIR_DATA or EVENT_SKY_DATA (which ever one the tempest goes).  I was thinking of putting it just below visibility in both.
Sky:
```
data["battery_level"] = await cnv.battery_level(obs[8])
```
Tempest:
```
data["battery_level"] = await cnv.battery_level(obs[16])
```
Air:
```
data["battery_level"] = await cnv.battery_level(obs[6])
```
As for making this the state of battery....I think I could do way more damage than good in the battery sensor area.

**Comment by GlennGoddard** [comment]
Also not sure how to set device class in const.py
Is there anything I am missing that needs updating?
helpers.py
const.py
weatherflow_mqtt.py

**Comment by briis** [comment]
Hi Glenn,
If you submit the helpers.py with your function, then let me do the other parts. Just make sure to comment what values you need passed. I can then make a `dev` container and we can start testing.

**Comment by GlennGoddard** [comment]
PR submitted with inputs required

**Comment by GlennGoddard** [comment]
Working for Tempest

**Comment by GlennGoddard** [comment]
Should I close this or wait for Air & Sky confirmation?

The battery level was picked up my the MQTT Integration in HA to show the battery state in the display, makes it look more complete.

**Comment by briis** [comment]
You can close it. I will test it on AIR & SKY.
