### ISSUE TITLE
Same topic for multiple devices.

### ISSUE THREAD

**Issue by olonsoft** [briis/hass-weatherflow2mqtt#66]
I am trying this container with my old SKYs and AIRs and I can get the observations ok.
But I have registered on my hub, 3 SKYs and 2 AIRs but the MQTT topic `obs_sky`  `rapid_wind` and `obs_air` report the values of all these devices on the same topic. So I can not know what device reports what.
I think that it would be good to report on each of the above topics, the device id among the observation data.

**Comment by briis** [comment]
Thanks for reporting, I will have to look in to how to do this. 
To clarify: You have 1 Hub and then 3 SKY's and 2 AIR's attached to that. Correct?

I might need to add the name and/or the device ID to the Topic, to separate them.

**Comment by olonsoft** [comment]
Yes exactly.
I think that it's a lot of work on your side. Because also the HA autodiscovery topics might have to change.

**Comment by briis** [comment]
Yes, you are right. This will a breaking change for all, as the sensor names  will change.
However, without having tested it, I already use the serial number of the unit as part of the Unique ID of the sensor, so there should be a change to just rename the sensors.
I will not implement it now, but I will keep it open, for future development, if/when there are other major changes that need to be done anyway.

**Comment by olonsoft** [comment]
Perfect!

**Comment by briis** [comment]
With the release of V3.0, this is now fixed. The system will now create sensors for each physical device attached to the Hub.
Closing the issue.

**Comment by Vertikar** [comment]
Great, thanks for the update!
