### ISSUE TITLE
Unable to install on ARM architecture (Raspberry Pi in my case)

### ISSUE THREAD

**Issue by simonranson** [briis/hass-weatherflow2mqtt#7]
Hello,

Just capturing the issue as discussed over on the [Weatherflow forum](https://community.weatherflow.com/t/weatherflow2mqtt-for-home-assistant/13718
).

I tried to install hass-weatherflow2mqtt on Docker running on a Raspberry Pi, however it would not run due to incorrect architecture. 

I followed the instructions posted by @briis over on the Weatherflow forum to build the container myself on the Pi. This worked well, and I got the add-on working.

Not wanting to stop there, I started to look into Docker a little more. The Pi I was using was a little overloaded but the one running HASS is an 8GB Pi4 - I found that Home Assistant OS essentially runs inside Docker, so I loaded up the Portainer community add-on to access the HA Docker environment. 

With some back-and-forth I have managed to get hass-weatherflow2mqtt running inside Docker directly on the HA Raspberry Pi. 

I've still got some tweaking to do, but I'll document the steps here.

Cheers
Simon

**Comment by briis** [comment]
Great work Simon. Looking forward to your description. Thanks

**Comment by simonranson** [comment]
Here's how I got it working...

To create PI Image, steps 1-3 as per @briis' instructions:

1.	On a Pi with Docker installed, download the source from Github to the Pi.
2.	Unpack the ZipFile, and go to the directory where you find the file Dockerfile
3.	Build the container locally by issuing this command: `docker build -t weatherflow2mqtt .` (don’t forget the . at the end of the command).

I now wanted to get this ready to use in Portainer, but couldn’t work our how to move files from one system to another, so I created an account at https://hub.docker.com/ and uploaded it there as follows:

1.	On the Pi used above ran command: `docker login`
2.	Tagged PI image with version number with command: `docker tag weatherflow2mqtt simonranson/tag weatherflow2mqtt:v1`
3.	Pushed PI image with command: `docker push simonranson/tag weatherflow2mqtt:v1`

I’ll delete this image once from docker.com I find a way to move files in Portainer.

Now onto the HA machines. This assumes the Mosquitto broker is already installed in HA

1.	In HA, install the “Portainer” and “Samba Share” add-ons.
2.	In the Samba Share configuration, set a username and password, then start the add-on
3.	On another machine on the network, browse to the IP/hostname of your HA server, and enter the credentials as per step 2.
4.	Create a folder for the integration to use. I created a folder called weatherflow under `\config\custom_components`.
5.	Start the Portainer add-on (you do need to disable protection mode to do this).

You can now open up the Portainer GUI and prepare the volume

6.	In Portainer, navigate to “Volumes” in the left hand column and click on the blue “+ Add volume”
7.	Give it a name, I used Weatherflow
8.	Turn on CIFS
9.	In the Address box, enter the IP/Hostname of your HA server
10.	In the Share box, the path from step 4 above (watch the “/” direction here), for my setup this was `/config/custom_components/weatherflow`
11.	Username and Password are as per step 2 above.

Now to add the container…

12.	Navigate to “Containers” on the left, and click the blue “+ Add container”
13.	Give it a name such as `weatherflow2mqtt`.
14.	Make sure “DockerHub” is selected in the Registry box, then use `simonranson/weatherflow2mqtt:v1` as the image name
15.	For now, just accept all the defaults for everything else and click “Deploy the container”

After a little while, the container will install, you will be able to see this by clicking the Containers link on the left. It’ll now need configuring.

16.	Navigate to “Containers” on the left, and click the`weatherflow2mqtt` container.
17.	Click the blue “Duplicate/Edit” button in the top right.
18.	Scroll down to the “Advanced Container Settings”
19.	Click “Volume” and click “map additional volume”
20.	Make sure “Volume” and “Writable” are selected on the right (darker blue colour)
21.	In Container enter: `/usr/local/config`
22.	In Volume use the drop-down to select your volume created in step 7
23.	Click “Network” and use the drop-down to select “host”
24.	Click “Restart policy” and select “Unless Stopped”
25.	Finally, head back to “Env” and set all your variables as per the Github instructions, ignore anything above TZ.
26.	Last thing to do now is press the “Deploy the container” button. Press “Replace” to the are you sure message.

Now if you look back in the containers section, you’ll see the state green/running. If you click the left most quick-action link you should see some activity. You can run through steps 16+ to go back in and set the debugs to true if you are having issues – don’t forget step 26 to redeploy if you make any changes.

Hope this helps anybody wanting a play.

Thanks again for all your hard work in writing the integration

Cheers
Simon

**Comment by briis** [comment]
Wow Simon, this is detailed. Thanks a lot for making the effort of writing this up.

**Comment by briis** [comment]
Just a quick note. I have just updated the code, to fix some errors. If you are not pulling the Forecast, the errors might not have hit you.

**Comment by simonranson** [comment]
Thank you - I'll grab your new update, build for ARM and test here too.

Cheers
Simon

**Comment by briis** [comment]
I will close this issue now Simon, as I have copied your instructions to the Discussion area, and also linked to that area in the Community.
