### ISSUE TITLE
Device has reported a sensor fault. Reason: ['wind failed']

### ISSUE THREAD

**Issue by WhistleMaster** [briis/hass-weatherflow2mqtt#71]
Hi !

Thanks for the great work on this docker !

I have the following error coming in the log: `DEBUG:weatherflow2mqtt.weatherflow_mqtt:Device XXX has reported a sensor fault. Reason: ['wind failed']`

I'm not sure what it means as the wind sensor is correctly reporting the information.

Kind regards,

**Comment by briis** [comment]
You are welcome.
The above log entry is produced by the Device itself, and send to the Hub, that then sends it to WeatherFlow. If you only get this a few times, don't worry, it might just be a glitch and as you state, the sensor is still reporting correctly. 

So unless you start to see a lot of errors like that, just ignore it.

**Comment by WhistleMaster** [comment]
Unfortunately, I get the error almost every minute 😕

**Comment by briis** [comment]
So basically, every time your Tempest device sends data. As I said, it is not something i can do anything with, as I just report the data. I suggest you contact WeatherFlow support and ask them.

**Comment by WhistleMaster** [comment]
I'll contact them, thanks 😊

**Comment by WhistleMaster** [comment]
Something I've noticed though, is that, in the application, I see the `Sensor Status` is `LIGHTNING_DISTURBER` 🤔

**Comment by briis** [comment]
LIGHTNING_DISTURBER can occur if the sensor detects some thing that is NOT lightning, but still sends out an electrical signal. If you have your device close to a Power Cable, or a Microwave oven that could trigger this.

**Comment by WhistleMaster** [comment]
The question I have is why the status reported by weatherflow2mqtt is different from the one reported by the official app 😅

**Comment by briis** [comment]
I never see these messages in the official APP also. I think they are just reported back to WeatherFlow, that then uses it for optimizing their algorithms. I could make a setting that removes them from the log?

**Comment by WhistleMaster** [comment]
I'm not sure but I think that could be useful to get information about sensors status.

**Comment by briis** [comment]
It was just if it is flooding the Log File, then it could be removed. As I said, this is not really related to the functionality of this program, I just decided to display the info, now that I saw the data coming in, but the entries are not used by the program itself, and as long as the device is reporting data, this can safely be ignored.

**Comment by WhistleMaster** [comment]
I think indeed that the info could be removed from the docker log. 

However, my point was that your mapping for the error bits seems to be incorrect. I've made a quick python script based on the UDP API to illustrate:

My device status is "131076". Using your implementation:

```
DEVICE_STATUS = [
    "lightning failed",
    "lightning noise",
    "lightning disturber",
    "pressure failed",
    "temperature failed",
    "rh failed",
    "wind failed",
    "precip failed",
    "light/uv failed",
]

def device_status(value):
    """Return device status as string."""
    if value is None:
        return
        
    binvalue = str(bin(value))
    binarr = binvalue[::-1]
    binarr = binarr[:len(DEVICE_STATUS)]
    return_value = []
    for x in range(len(DEVICE_STATUS)):
        if binarr[len(binarr) - 1 - x] == "1":
            return_value.append(DEVICE_STATUS[x])

    return return_value

print(device_status(131076))
```
This gives `['wind failed']`.

However, based on the API [here](https://weatherflow.github.io/Tempest/api/udp/v170/) `Status (device) [type = device_status]`, I've made the following:

```
masks = {
        0b000000001: 'Lightning',
        0b000000010: 'LightningNoise',
        0b000000100: 'LightningDisturber',
        0b000001000: 'Pressure',
        0b000010000: 'Temperature',
        0b000100000: 'Humidity',
        0b001000000: 'Wind',
        0b010000000: 'Precipitation',
        0b100000000: 'Light/UV',
        0x00008000: 'power booster depleted',
        0x00010000: 'power booster shore power'
}

def device_status_new(value):
    failed = []

    for mask in masks:
        if mask & value:
            failed.append(masks[mask])
    
    return failed

print(device_status_new(131076))
```
This gives `['LightningDisturber']` which is correct and the same as the official tempest iOS app.

Hope it clarify a bit 🙂

**Comment by briis** [comment]
GOT IT, thanks. I will fix this based on your program above. Thanks

**Comment by WhistleMaster** [comment]
Great thanks ! 

Would it be possible to add two new sensors for the hub itself and for the device itself with information (attributes) such as sensor errors, firmware version, etc. ?

**Comment by briis** [comment]
I have edited it now, and will build new containers. They will be uploaded to the new `dev` tag, which I use before releasing new versions. This tag will always be the latest version, but might have bugs in it. So if you could test it, I would appreciate it.

> Would it be possible to add two new sensors for the hub itself and for the device itself with information (attributes) such as sensor errors, firmware version, etc. ?

Yes, but please create a new Issue for this, specifying what you would like to see in these sensors.

**Comment by briis** [comment]
`dev` tag now has this implemented.

**Comment by WhistleMaster** [comment]
Perfect, will test it, thanks !

I've made another request for the sensors 😊

**Comment by WhistleMaster** [comment]
> `dev` tag now has this implemented.

I've tested it and it's working fine for the error now:

`DEBUG:weatherflow2mqtt.weatherflow_mqtt:Device XXX has reported a sensor fault. Reason: ['LightningDisturber']`

Thanks !

**Comment by WhistleMaster** [comment]
Just a quick one, I have the docker variable `DEBUG` to `False`, so this kind of information should not be displayed in the log.

**DEBUG**:weatherflow2mqtt.weatherflow_mqtt
