### ISSUE TITLE
Request: sensor for hub and device

### ISSUE THREAD

**Issue by WhistleMaster** [briis/hass-weatherflow2mqtt#73]
Hi !

It would be great to have two additional sensors, one for the hub and one for the device, each with the available attributes.

**Examples**
```
Status (device) [type = device_status]

	{
	  "serial_number": "AR-00004049",
	  "type": "device_status",
	  "hub_sn": "HB-00000001",
	  "timestamp": 1510855923,
	  "uptime": 2189,
	  "voltage": 3.50,
	  "firmware_revision": 17,
	  "rssi": -17,
	  "hub_rssi": -87,
	  "sensor_status": 0,
	  "debug": 0
	}
```

```
Status (hub) [type = hub_status]

	{
	  "serial_number":"HB-00000001",
	  "type":"hub_status",
	  "firmware_revision":"35",
	  "uptime":1670133,
	  "rssi":-62,
	  "timestamp":1495724691,
	  "reset_flags": "BOR,PIN,POR",
	  "seq": 48,
	  "fs": [1, 0, 15675411, 524288],
          "radio_stats": [2, 1, 0, 3, 2839],
          "mqtt_stats": [1, 0]
	}

```

`fs` and `mqtt_stats` seems to be for internal use, not sure if they would make any sense here.

**reset_flags values**

Value | Description
-- | --
BOR | Brownout reset
PIN | PIN reset
POR | Power reset
SFT | Software reset
WDG | Watchdog reset
WWD | Window watchdog reset
LPW | Low-power reset
HRDFLT | Hard fault detected

**radio_stats values**

Index | Field
-- | --
0 | Version
1 | Reboot Count
2 | I2C Bus Error Count
3 | Radio Status (0 = Radio Off, 1 = Radio On, 3 = Radio Active, 7 = BLE Connected)
4 | Radio Network ID

Thanks !
Regards,

**Comment by briis** [comment]
Closing as this is released with V2.2.0
