### ISSUE TITLE
Request: use DEBUG env var

### ISSUE THREAD

**Issue by WhistleMaster** [briis/hass-weatherflow2mqtt#74]
Hi again !

It seems that the DEBUG env var is not used everywhere to display or not information through `_LOGGER.debug`.

As an example [377](https://github.com/briis/hass-weatherflow2mqtt/blob/dd25abea85bc0ebd10f7d20fa2ec7d59a326e41a/weatherflow2mqtt/weatherflow_mqtt.py#L377) is not testing the `show_debug` var.

Thanks !
Kind regards,

**Comment by briis** [comment]
You are right. I will go through the code, and add where needed.

**Comment by briis** [comment]
This is done, so I close it.
