### ISSUE TITLE
Wrong unit of measurement for temperature

### ISSUE THREAD

**Issue by Bo1jo** [briis/hass-weatherflow2mqtt#78]
Unit of measurement for temperature should be °C and not ˚C. The difference is a problem for exempel when using min/max-sensors as the unit of measurement for the wf-sensor isn't the same as for other temperature sensors in HA.

**Comment by briis** [comment]
Ok, thanks for the info. What is the ASCII value for the degree symbol you have above?

**Comment by Bo1jo** [comment]
<html>
<body>


Char | Dec | Hex | Oct
° | 176 | B0 | 260

<br class="Apple-interchange-newline">
</body>
</html>

Thanks for fast response and great code!

**Comment by briis** [comment]
I will make the change ASAP. Thanks

**Comment by briis** [comment]
Is now fixed. The changes are published to the docker container with the `dev` tag. I will wait for a few more changes to publish a new release.

**Comment by GlennGoddard** [comment]
Just letting you know that everything still seems to work for me using the latest dev build.
I did not check in the code but I would assume this would affect us imperial users also.

**Comment by briis** [comment]
Thanks Glenn. It was only the degree symbol in front of the C and F in the unit that was changed. So no formulas changed.

**Comment by briis** [comment]
Fixed. Currently in the `dev` container, but will be part of the next release.
