### ISSUE TITLE
sensor.wf_rain_intensity` not showing

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#85]
Hi guys

Just installed new image and ran docker and sensor.wf_rain_intensity not showing up not using a config file .....

Did i miss something else to set?

Thanks

**Comment by GlennGoddard** [comment]
Are you running the latest or the dev tag via docker?   Rain Intensity is new and is being tested in the dev build, once we know it works (which it does) and other items (which I will be checking this weekend) then @briis will move the dev build to the latest (stable) build and then it will be available to those running the latest tag.
