### ISSUE TITLE
Container constantly restarting keyerror: 'icon'

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#87]
Just started a little bit ago on latest version.  Anyone else?  It doesn't like something.

![Screen Shot 2021-10-18 at 1 46 05 PM](https://user-images.githubusercontent.com/42701104/137789725-cebb968c-1daa-4c5e-8f2b-210338b6b9a9.png)

**Comment by briis** [comment]
If it is at the weather sensor every time then it seems there is an issue pulling the forecast from the weatherflow site. 
Is your internet ok?

**Comment by briis** [comment]
Closing this issue as this seems to be resolved
