### ISSUE TITLE
False lightning strikes 

### ISSUE THREAD

**Issue by jake404** [briis/hass-weatherflow2mqtt#92]
Last night Weatherflow2MQTT reported several lightning strikes, but on the tempestwx.com site and in the Android app there are no reported lightning strikes.  It was clear skies and absolutely no chance of lightning in the area. Is it that Weatherflow2MQTT reads the raw data which includes electromagnetic noise and not filtered data from the Tempest service?

![image](https://user-images.githubusercontent.com/12189899/141474199-78618b81-628e-4beb-842e-6ee57bfb21b6.png)

**Comment by briis** [comment]
Yes, we read the data directly from the device, so it has not been filtered through the algorithm I assume WeatherFlow has. So you can get false positives. There are some flags in the `device_status` that reports `lightning noise` and `lightning disturber` so let me see what I can do with these.

But this is extremely hard to test, as the best result is no result, and that can happen for many reasons.

**Comment by jake404** [comment]
Ok, I understand. Yesterday it reported 69 strikes and today so far it reported 14 strikes. You can take a look at WeatherFlow Collector (https://github.com/lux4rd0/weatherflow-collector/) as it did not report any lightning. Maybe they have a filtering function.

WeatherFlow2MQTT also reported 50mm rain yesterday and there was no rain at all. Same thing with this as the lightning count, the Tempest website and Android app did not report any rain yesterday. Also, WeatherFlow Collector did not report any rain.

**Comment by briis** [comment]
It is strange though - I have had 1 false lightning strike in 6 month, and my rain data is pretty accurate, so I don't have this experience myself, nor has other people I work with on this project. Are you sure your station is online? I mean it might report local data but never transfer them to weatherflow? Is the light on the back of the Hub green?

**Comment by jake404** [comment]
Maybe there is more interference in my area.
Yes, they are online and I can see constant updates on all data in the app and on the website.

The rain went from 0 to 50mm instantly with clear skies:
![image](https://user-images.githubusercontent.com/12189899/141650294-09b0f3f2-f2a3-4bc7-a50f-2eafa61c3023.png)

**Comment by briis** [comment]
This is strange, and had to debug from my end as I cannot simulate the situation. But I will think about how I could maybe read the registers more often for debugging purposes.

**Comment by GlennGoddard** [comment]
I had an issue before with false lightning strikes and it was the Franklin sensor on the Tempest picking up electrical equipment noise.  I relocated a few feet and false strikes went away.  I was getting a false strike every 2 to 3 seconds.

**Comment by jake404** [comment]
I have been looking into this and have done some tests with my own UDP listener, websocket listener, and REST. It does seem that the UDP values are not filtered, but websocket and REST are filtered. So now I have created new entities with updates from both websocket and REST for lightning and precipitation. That would be a good addition to your integration.

**Comment by GlennGoddard** [comment]
As long as the filtered entities are separate from the local ones.  I would prefer to keep everything that can be local, local.  My concern is loosing functionality (information) WHEN the internet goes down.  I live in a heavily wooded area and falling trees on lines have been way to frequent lately; I have a generator so power is not a problem but internet is.

**Comment by jake404** [comment]
I completely understand, but what good is data if it's incorrect data? But I agree that they need to be separate.

**Comment by GlennGoddard** [comment]
It depends on how you use the data.  It might not be useful, by itself, for valid lightning detection; but it is useful to detect electrical problems in the area.

I do agree that in order to validate lighting that there must be multiple detections of the same event from different locations.
It is possibly valid data but applied to the incorrect source (i.e. lightning).

**Comment by briis** [comment]
I am not going to add more REST based sensors to this. As Glenn states this is meant to be local using UDP. BUT, I am close to releasing a new and re-written Integration supporting the REST API. (Just waiting for it to get merged in the HACS store)

If you want, you can test it now. Instructions are in the README. https://github.com/briis/hass-weatherflow

**Comment by jake404** [comment]
Contradicting... but ok.

**Comment by briis** [comment]
> Contradicting... but ok.

Not sure what you mean by that? All sensors of this Add-On are created using the UDP protocol on the local network, and that was the whole purpose - having something that does not require a working Internet connection. With one exception: The Forecast data, which is optional but does require an Internet connection.

The other Integration is purely REST based, and does require an Internet connection. So there is an option for everything.
