### ISSUE TITLE
battery state also as percent

### ISSUE THREAD

**Issue by leonardpitzu** [briis/hass-weatherflow2mqtt#95]
having a battery state card requires for the battery to have actual percentage instead of voltage or it looks like in the pic attached and one can't really use it in generic percentage-based automation.
<img width="475" alt="Screenshot 2021-11-15 at 14 30 49" src="https://user-images.githubusercontent.com/4321813/141782517-091015b6-148f-453f-ab8e-e873b4a97fec.png">

something like this might do it:
`                      if self._airbattery < 1.6:
                            ds.airbattery = 5
                        elif self._airbattery < 1.7:
                            ds.airbattery = 10
                        elif self._airbattery < 1.8:
                            ds.airbattery = 20
                        elif self._airbattery < 1.9:
                            ds.airbattery = 30
                        elif self._airbattery < 2.0:
                            ds.airbattery = 40
                        elif self._airbattery < 2.1:
                            ds.airbattery = 50
                        elif self._airbattery < 2.2:
                            ds.airbattery = 60
                        elif self._airbattery < 2.3:
                            ds.airbattery = 70
                        elif self._airbattery < 2.4:
                            ds.airbattery = 80
                        elif self._airbattery < 2.5:
                            ds.airbattery = 90
                        else:
                            ds.airbattery = 100`

**Comment by leonardpitzu** [comment]
never mind, it's already in there.

**Comment by briis** [comment]
Yes. I can't remember if it is as detailed as your suggestion, but I will look at the formula we use and see if it needs adjustment.
